version: 1
captured_at: '2026-03-15T19:47:46.339077+00:00'
schema:
  nodes:
    AnatomicalEntity:
      properties:
        id: string
        name: string
        preferred_id: string
    BiologicalEntity:
      properties:
        annotation_score: float
        cofactor_names: list
        eggnog_ids: string
        gene_names: list
        go_biological_processes: list
        id: string
        is_reviewed: string
        keyword_ids: list
        keywords: list
        locus_tag: string
        molecular_mass: int
        pfam_ids: list
        preferred_id: string
        protein_family: string
        protein_synonyms: string
        proteome_ids: list
        refseq_ids: list
        sequence_length: int
        string_ids: string
        transmembrane_regions: list
    BiologicalProcess:
      properties:
        id: string
        name: string
        preferred_id: string
    BiologicalProcessOrActivity:
      properties:
        id: string
        name: string
        preferred_id: string
    CellularComponent:
      properties:
        id: string
        name: string
        preferred_id: string
    CogFunctionalCategory:
      properties:
        code: string
        id: string
        name: string
        preferred_id: string
    CyanorakRole:
      properties:
        code: string
        description: string
        id: string
        preferred_id: string
    Cyanorak_cluster:
      properties:
        cluster_number: string
        id: string
        preferred_id: string
    EcNumber:
      properties:
        alternate_name: list
        catalytic_activity: list
        comments: list
        id: string
        name: string
        preferred_id: string
    Entity:
      properties:
        code: string
        id: string
        name: string
        preferred_id: string
    EnvironmentalCondition:
      properties:
        co2_level: string
        condition_category: string
        condition_type: string
        description: string
        id: string
        light_condition: string
        light_intensity: string
        medium: string
        name: string
        oxygen_level: string
        preferred_id: string
        publications: list
        temperature: string
    EnvironmentalFeature:
      properties:
        co2_level: string
        condition_category: string
        condition_type: string
        description: string
        id: string
        light_condition: string
        light_intensity: string
        medium: string
        name: string
        oxygen_level: string
        preferred_id: string
        publications: list
        temperature: string
    Gene:
      properties:
        all_identifiers: list
        alternate_functional_descriptions: list
        alternative_locus_tags: list
        annotation_quality: int
        cluster_number: string
        cog_category: list
        cyanorak_Role: list
        cyanorak_Role_description: list
        eggnog_ogs: list
        end: int
        end_cyanorak: int
        function_description: string
        function_description_source: string
        gene_category: string
        gene_summary: string
        gene_synonyms: list
        id: string
        locus_tag: string
        locus_tag_cyanorak: string
        locus_tag_ncbi: string
        max_annot_lvl: string
        old_locus_tags: list
        organism_strain: string
        pfam_descriptions: list
        preferred_id: string
        product: string
        product_cyanorak: string
        product_source: string
        protein_id: string
        seed_ortholog: string
        seed_ortholog_evalue: float
        signal_peptide: string
        start: int
        start_cyanorak: int
        strand: string
        strand_cyanorak: string
        tIGR_Role: list
        tIGR_Role_description: list
        transmembrane_regions: list
    GeneOntology:
      properties:
        id: string
        name: string
        preferred_id: string
    GroupingClass:
      properties:
        cluster_number: string
        id: string
        preferred_id: string
    InformationContentEntity:
      properties:
        abstract: string
        authors: list
        description: string
        doi: string
        id: string
        journal: string
        organism: list
        preferred_id: string
        publication_year: int
        study_type: string
        title: string
    KeggTerm:
      properties:
        id: string
        level: string
        name: string
        preferred_id: string
    MolecularFunction:
      properties:
        id: string
        name: string
        preferred_id: string
    NamedThing:
      properties:
        code: string
        id: string
        name: string
        preferred_id: string
    OrganismTaxon:
      properties:
        clade: string
        family: string
        genus: string
        id: string
        kingdom: string
        lineage: string
        ncbi_taxon_id: int
        order: string
        organism_name: string
        phylum: string
        preferred_id: string
        preferred_name: string
        species: string
        strain_name: string
        superkingdom: string
        tax_class: string
    OrganismalEntity:
      properties:
        id: string
        name: string
        preferred_id: string
    Polypeptide:
      properties:
        annotation_score: float
        cofactor_names: list
        eggnog_ids: string
        gene_names: list
        go_biological_processes: list
        id: string
        is_reviewed: string
        keyword_ids: list
        keywords: list
        locus_tag: string
        molecular_mass: int
        pfam_ids: list
        preferred_id: string
        protein_family: string
        protein_synonyms: string
        proteome_ids: list
        refseq_ids: list
        sequence_length: int
        string_ids: string
        transmembrane_regions: list
    Protein:
      properties:
        annotation_score: float
        cofactor_names: list
        eggnog_ids: string
        gene_names: list
        go_biological_processes: list
        id: string
        is_reviewed: string
        keyword_ids: list
        keywords: list
        locus_tag: string
        molecular_mass: int
        pfam_ids: list
        preferred_id: string
        protein_family: string
        protein_synonyms: string
        proteome_ids: list
        refseq_ids: list
        sequence_length: int
        string_ids: string
        transmembrane_regions: list
    Publication:
      properties:
        abstract: string
        authors: list
        description: string
        doi: string
        id: string
        journal: string
        organism: list
        preferred_id: string
        publication_year: int
        study_type: string
        title: string
    Schema_info:
      properties:
        id: string
        preferred_id: string
        schema_info: string
    TigrRole:
      properties:
        code: string
        description: string
        id: string
        preferred_id: string
  relationships:
    Biological_process_is_a_biological_process:
      source_labels:
      - BiologicalEntity
      - BiologicalProcess
      - BiologicalProcessOrActivity
      - Entity
      - GeneOntology
      - NamedThing
      target_labels:
      - BiologicalEntity
      - BiologicalProcess
      - BiologicalProcessOrActivity
      - Entity
      - GeneOntology
      - NamedThing
      properties: {}
    Biological_process_negatively_regulates_biological_process:
      source_labels:
      - BiologicalEntity
      - BiologicalProcess
      - BiologicalProcessOrActivity
      - Entity
      - GeneOntology
      - NamedThing
      target_labels:
      - BiologicalEntity
      - BiologicalProcess
      - BiologicalProcessOrActivity
      - Entity
      - GeneOntology
      - NamedThing
      properties: {}
    Biological_process_part_of_biological_process:
      source_labels:
      - BiologicalEntity
      - BiologicalProcess
      - BiologicalProcessOrActivity
      - Entity
      - GeneOntology
      - NamedThing
      target_labels:
      - BiologicalEntity
      - BiologicalProcess
      - BiologicalProcessOrActivity
      - Entity
      - GeneOntology
      - NamedThing
      properties: {}
    Biological_process_positively_regulates_biological_process:
      source_labels:
      - BiologicalEntity
      - BiologicalProcess
      - BiologicalProcessOrActivity
      - Entity
      - GeneOntology
      - NamedThing
      target_labels:
      - BiologicalEntity
      - BiologicalProcess
      - BiologicalProcessOrActivity
      - Entity
      - GeneOntology
      - NamedThing
      properties: {}
    Cellular_component_is_a_cellular_component:
      source_labels:
      - AnatomicalEntity
      - BiologicalEntity
      - CellularComponent
      - Entity
      - NamedThing
      - OrganismalEntity
      target_labels:
      - AnatomicalEntity
      - BiologicalEntity
      - CellularComponent
      - Entity
      - NamedThing
      - OrganismalEntity
      properties: {}
    Cellular_component_part_of_cellular_component:
      source_labels:
      - AnatomicalEntity
      - BiologicalEntity
      - CellularComponent
      - Entity
      - NamedThing
      - OrganismalEntity
      target_labels:
      - AnatomicalEntity
      - BiologicalEntity
      - CellularComponent
      - Entity
      - NamedThing
      - OrganismalEntity
      properties: {}
    Coculture_changes_expression_of:
      source_labels:
      - Entity
      - NamedThing
      - OrganismTaxon
      target_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      properties:
        adjusted_p_value: float
        analysis_name: string
        control_condition: string
        experimental_context: string
        expression_direction: string
        id: string
        log2_fold_change: float
        omics_type: string
        organism_strain: string
        publications: list
        significant: string
        statistical_test: string
        time_point: string
        treatment_condition: string
    Coculture_changes_expression_of_ortholog:
      source_labels:
      - Entity
      - NamedThing
      - OrganismTaxon
      target_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      properties:
        analysis_name: string
        control_condition: string
        distance: string
        experimental_context: string
        expression_direction: string
        homology_cluster_id: string
        homology_source: string
        log2_fold_change: float
        omics_type: string
        organism_strain: string
        original_gene: string
        publications: list
        significant: string
        statistical_test: string
        time_point: string
        treatment_condition: string
    Condition_changes_expression_of:
      source_labels:
      - EnvironmentalCondition
      - EnvironmentalFeature
      target_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      properties:
        adjusted_p_value: float
        analysis_name: string
        control_condition: string
        experimental_context: string
        expression_direction: string
        id: string
        log2_fold_change: float
        omics_type: string
        organism_strain: string
        publications: list
        significant: string
        statistical_test: string
        time_point: string
        treatment_condition: string
    Condition_changes_expression_of_ortholog:
      source_labels:
      - EnvironmentalCondition
      - EnvironmentalFeature
      target_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      properties:
        adjusted_p_value: float
        analysis_name: string
        control_condition: string
        distance: string
        experimental_context: string
        expression_direction: string
        homology_cluster_id: string
        homology_source: string
        log2_fold_change: float
        omics_type: string
        organism_strain: string
        original_gene: string
        publications: list
        significant: string
        statistical_test: string
        time_point: string
        treatment_condition: string
    Cyanorak_role_is_a_cyanorak_role:
      source_labels:
      - CyanorakRole
      - Entity
      - NamedThing
      target_labels:
      - CyanorakRole
      - Entity
      - NamedThing
      properties:
        id: string
    Ec_number_is_a_ec_number:
      source_labels:
      - EcNumber
      - Entity
      - NamedThing
      target_labels:
      - EcNumber
      - Entity
      - NamedThing
      properties: {}
    Gene_belongs_to_organism:
      source_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      target_labels:
      - Entity
      - NamedThing
      - OrganismTaxon
      properties:
        id: string
    Gene_catalyzes_ec_number:
      source_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      target_labels:
      - EcNumber
      - Entity
      - NamedThing
      properties:
        id: string
    Gene_enables_molecular_function:
      source_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      target_labels:
      - BiologicalEntity
      - BiologicalProcessOrActivity
      - Entity
      - MolecularFunction
      - NamedThing
      properties:
        id: string
    Gene_encodes_protein:
      source_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      target_labels:
      - BiologicalEntity
      - Entity
      - NamedThing
      - Polypeptide
      - Protein
      properties:
        licence: string
        source: string
        version: string
    Gene_has_cyanorak_role:
      source_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      target_labels:
      - CyanorakRole
      - Entity
      - NamedThing
      properties:
        id: string
    Gene_has_kegg_ko:
      source_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      target_labels:
      - Entity
      - KeggTerm
      - NamedThing
      properties:
        id: string
    Gene_has_tigr_role:
      source_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      target_labels:
      - Entity
      - NamedThing
      - TigrRole
      properties:
        id: string
    Gene_in_cog_category:
      source_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      target_labels:
      - CogFunctionalCategory
      - Entity
      - NamedThing
      properties:
        id: string
    Gene_in_cyanorak_cluster:
      source_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      target_labels:
      - Cyanorak_cluster
      - GroupingClass
      properties:
        id: string
    Gene_involved_in_biological_process:
      source_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      target_labels:
      - BiologicalEntity
      - BiologicalProcess
      - BiologicalProcessOrActivity
      - Entity
      - GeneOntology
      - NamedThing
      properties:
        id: string
    Gene_is_homolog_of_gene:
      source_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      target_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      properties:
        cluster_id: string
        distance: string
        source: string
    Gene_located_in_cellular_component:
      source_labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      target_labels:
      - AnatomicalEntity
      - BiologicalEntity
      - CellularComponent
      - Entity
      - NamedThing
      - OrganismalEntity
      properties:
        id: string
    Kegg_term_is_a_kegg_term:
      source_labels:
      - Entity
      - KeggTerm
      - NamedThing
      target_labels:
      - Entity
      - KeggTerm
      - NamedThing
      properties:
        id: string
    Molecular_function_is_a_molecular_function:
      source_labels:
      - BiologicalEntity
      - BiologicalProcessOrActivity
      - Entity
      - MolecularFunction
      - NamedThing
      target_labels:
      - BiologicalEntity
      - BiologicalProcessOrActivity
      - Entity
      - MolecularFunction
      - NamedThing
      properties: {}
    Molecular_function_part_of_molecular_function:
      source_labels:
      - BiologicalEntity
      - BiologicalProcessOrActivity
      - Entity
      - MolecularFunction
      - NamedThing
      target_labels:
      - BiologicalEntity
      - BiologicalProcessOrActivity
      - Entity
      - MolecularFunction
      - NamedThing
      properties: {}
    Protein_belongs_to_organism:
      source_labels:
      - BiologicalEntity
      - Entity
      - NamedThing
      - Polypeptide
      - Protein
      target_labels:
      - Entity
      - NamedThing
      - OrganismTaxon
      properties:
        licence: string
        source: string
        version: string
    Published_expression_data_about:
      source_labels:
      - Entity
      - InformationContentEntity
      - NamedThing
      - Publication
      target_labels:
      - Entity
      - EnvironmentalCondition
      - EnvironmentalFeature
      - NamedThing
      - OrganismTaxon
      properties:
        id: string
        licence: string
        source: string
        version: string
