"""Snapshot the live ControlledVocabulary values the docs quote.

Writes ``multiomics_explorer/inputs/lint/vocab_snapshot.yaml`` — the offline
source for ``tests/unit/test_docs_lint.py::test_vocab_values_in_docs`` (every
vocabulary value quoted in docs / parameter descriptions must be a live value).
``tests/integration/test_docs_kg_claims.py::test_vocab_snapshot_matches_live``
(``-m kg``) fails loudly when a KG rebuild changes the vocabulary; re-run this
script and commit the diff.

Usage:
    uv run python scripts/snapshot_vocab.py            # write the snapshot
    uv run python scripts/snapshot_vocab.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
SNAPSHOT_PATH = REPO / "multiomics_explorer" / "inputs" / "lint" / "vocab_snapshot.yaml"

# Properties whose values the docs quote in prose / call examples. Every
# (property, applies_to) pair the KG carries for these is captured.
SNAPSHOT_PROPERTIES = [
    "treatment_type",
    "background_factors",
    "compartment",
    "omics_type",
    "table_scope",
    "growth_phase",
    "value_kind",
    "detection_status",
    "evidence",
    "sources",
    "substrate_depth",
    "attachment_depth",
    "cluster_type",
]

_VOCAB_CYPHER = (
    "MATCH (v:ControlledVocabulary) WHERE v.property IN $props "
    "RETURN v.property AS property, v.applies_to AS applies_to, "
    "toString(v.closed) AS closed, v.values AS values "
    "ORDER BY property, applies_to"
)
_BUILT_AT_CYPHER = "MATCH (s:Schema_info) RETURN s.built_at AS built_at LIMIT 1"


def snapshot_vocab(conn) -> dict:
    """Read the live vocabulary into the snapshot shape.

    ``conn`` is anything with ``execute_query(cypher, timeout=..., **params)``
    (``GraphConnection``). Returns ``{"kg_built_at": str | None,
    "vocabularies": {property: {applies_to: {"closed": bool, "values": [...]}}}}``.
    Values are sorted so the file diff is stable across rebuilds.
    """
    built = conn.execute_query(_BUILT_AT_CYPHER, timeout=30)
    rows = conn.execute_query(_VOCAB_CYPHER, timeout=60, props=SNAPSHOT_PROPERTIES)
    vocab: dict[str, dict[str, dict]] = {}
    for r in rows:
        vocab.setdefault(r["property"], {})[r["applies_to"]] = {
            "closed": r["closed"] == "true",
            "values": sorted(r["values"] or []),
        }
    return {
        "kg_built_at": built[0]["built_at"] if built else None,
        "vocabularies": vocab,
    }


def render(snapshot: dict) -> str:
    header = (
        "# GENERATED by scripts/snapshot_vocab.py — do not edit by hand.\n"
        "# Live ControlledVocabulary values for the properties the docs quote.\n"
        "# tests/unit/test_docs_lint.py reads this offline; the -m kg test in\n"
        "# tests/integration/test_docs_kg_claims.py asserts it matches the live KG.\n"
    )
    return header + yaml.safe_dump(snapshot, sort_keys=True, allow_unicode=True)


def load_snapshot(path: Path = SNAPSHOT_PATH) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if the snapshot is stale")
    ap.add_argument("--out", type=Path, default=SNAPSHOT_PATH)
    args = ap.parse_args(argv)

    from multiomics_explorer.kg.connection import GraphConnection

    live = snapshot_vocab(GraphConnection())
    if args.check:
        current = load_snapshot(args.out) if args.out.exists() else None
        if current == live:
            print(f"{args.out.relative_to(REPO)} is current (kg_built_at={live['kg_built_at']})")
            return 0
        print(f"{args.out.relative_to(REPO)} is stale — run scripts/snapshot_vocab.py")
        return 1
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(live), encoding="utf-8")
    n = sum(len(v) for v in live["vocabularies"].values())
    print(f"wrote {args.out.relative_to(REPO)}: {n} (property, applies_to) pairs, "
          f"kg_built_at={live['kg_built_at']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
