"""Curated gene fixtures from KG build cache for correctness testing.

Generated by scripts/build_test_fixtures.py — do not edit manually.
Source: multiomics_biocypher_kg/cache/data/*/genomes/*/gene_annotations_merged.json
"""

# Full gene records as they appear in annotation JSONs
GENES = [
    {
        "all_identifiers": [
            "CK_Pro_MED4_00001",
            "Q7V3R7",
            "TX50_RS00020",
            "WP_011131639.1"
        ],
        "alternate_functional_descriptions": [
            "[cyanorak] DNA polymerase III, beta subunit",
            "[ncbi] DNA polymerase III subunit beta",
            "[eggnog] Confers DNA tethering and processivity to DNA polymerases and other proteins. Acts as a clamp, forming a ring around DNA (a reaction catalyzed by the clamp-loading complex) which diffuses in an ATP-independent manner freely and bidirectionally along dsDNA. Initially characterized for its ability to contact the catalytic subunit of DNA polymerase III (Pol III), a complex, multichain enzyme responsible for most of the replicative synthesis in bacteria",
            "[uniprot] Confers DNA tethering and processivity to DNA polymerases and other proteins. Acts as a clamp, forming a ring around DNA (a reaction catalyzed by the clamp-loading complex) which diffuses in an ATP-independent manner freely and bidirectionally along dsDNA. Initially characterized for its ability to contact the catalytic subunit of DNA polymerase III (Pol III), a complex, multichain enzyme responsible for most of the replicative synthesis in bacteria; Pol III exhibits 3^-5^ exonuclease proofreading activity. The beta chain is required for initiation of replication as well as for processivity of DNA replication",
            "[protein_family] Beta sliding clamp family",
            "[cyanorak_role] DNA replication, recombination, and repair",
            "[tigr_role] DNA metabolism / DNA replication, recombination, and repair",
            "[cog] COG: INFORMATION STORAGE AND PROCESSING [L] Replication, recombination and repair",
            "[cog] bactNOG: INFORMATION STORAGE AND PROCESSING [L] Replication, recombination and repair",
            "[cog] cyaNOG: INFORMATION STORAGE AND PROCESSING [L] Replication, recombination and repair",
            "[kegg] DNA-directed DNA polymerase; DNA polymerase I; DNA polymerase II; DNA polymerase III; DNA polymerase alpha; DNA polymerase beta; DNA polymerase gamma; DNA nucleotidyltransferase (DNA-directed); deoxyribonucleate nucleotidyltransferase; deoxynucleate polymerase; deoxyribonucleic acid duplicase; deoxyribonucleic acid polymerase; deoxyribonucleic duplicase; deoxyribonucleic polymerase; deoxyribonucleic polymerase I; DNA duplicase; DNA nucleotidyltransferase; DNA polymerase; DNA replicase; DNA-dependent DNA polymerase; duplicase; Klenow fragment; sequenase; Taq DNA polymerase; Taq Pol I; Tca DNA polymerase",
            "[pfam] DNA_pol3_beta: DNA polymerase III beta subunit, N-terminal domain",
            "[pfam] DNA_pol3_beta_3: DNA polymerase III beta subunit, C-terminal domain",
            "[pfam] DNA_pol3_beta_2: DNA polymerase III beta subunit, central domain"
        ],
        "alternative_locus_tags": [
            "PMM0001"
        ],
        "annotation_quality": 3,
        "bacteria_cog_og": "COG0592",
        "cluster_number": "CK_00000364",
        "cog_category": [
            "L"
        ],
        "cyanorak_Role": [
            "F.1"
        ],
        "cyanorak_Role_description": [
            "DNA replication, recombination, and repair"
        ],
        "ec_numbers": [
            "2.7.7.7"
        ],
        "eggnog_og_descriptions": [
            "COG: INFORMATION STORAGE AND PROCESSING [L] Replication, recombination and repair",
            "bactNOG: INFORMATION STORAGE AND PROCESSING [L] Replication, recombination and repair",
            "cyaNOG: INFORMATION STORAGE AND PROCESSING [L] Replication, recombination and repair"
        ],
        "eggnog_ogs": [
            "COG0592",
            "bactNOG00989",
            "cyaNOG01040",
            "COG0592@1|root",
            "COG0592@2|Bacteria",
            "1FZV5@1117|Cyanobacteria",
            "1MKTR@1212|Prochloraceae"
        ],
        "end": 1331,
        "end_cyanorak": 1331,
        "function_description": "Confers DNA tethering and processivity to DNA polymerases and other proteins. Acts as a clamp, forming a ring around DNA (a reaction catalyzed by the clamp-loading complex) which diffuses in an ATP-independent manner freely and bidirectionally along dsDNA. Initially characterized for its ability to contact the catalytic subunit of DNA polymerase III (Pol III), a complex, multichain enzyme responsible for most of the replicative synthesis in bacteria; Pol III exhibits 3^-5^ exonuclease proofreading activity. The beta chain is required for initiation of replication as well as for processivity of DNA replication",
        "function_description_source": "uniprot",
        "gene_category": "Replication and repair",
        "gene_name": "dnaN",
        "gene_name_source": "cyanorak",
        "gene_summary": "dnaN :: DNA polymerase III, beta subunit :: Confers DNA tethering and processivity to DNA polymerases and other proteins. Acts as a clamp, forming a ring around DNA (a reaction catalyzed by the clamp-loading complex) which diffuses in an ATP-independent manner freely and bidirectionally along dsDNA. Initially characterized for its ability to contact the catalytic subunit of DNA polymerase III (Pol III), a complex, multichain enzyme responsible for most of the replicative synthesis in bacteria; Pol III exhibits 3^-5^ exonuclease proofreading activity. The beta chain is required for initiation of replication as well as for processivity of DNA replication",
        "gene_synonyms": [
            "PMM0001"
        ],
        "go_term_descriptions": [
            "DNA replication",
            "DNA replication",
            "DNA polymerase activity",
            "DNA binding",
            "DNA-directed DNA polymerase activity",
            "3'-5' exonuclease activity",
            "DNA replication",
            "DNA polymerase activity",
            "DNA binding",
            "DNA-directed DNA polymerase activity",
            "3'-5' exonuclease activity",
            "DNA polymerase III complex"
        ],
        "go_terms": [
            "GO:0005737",
            "GO:0009360",
            "GO:0006271",
            "GO:0008408",
            "GO:0003677",
            "GO:0003887",
            "GO:0006260",
            "GO:0034061"
        ],
        "kegg_brite": [
            "ko00000",
            "ko00001",
            "ko00002",
            "ko01000",
            "ko03032",
            "ko03400"
        ],
        "kegg_ko": [
            "K02338"
        ],
        "kegg_ko_descriptions": [
            "DNA-directed DNA polymerase; DNA polymerase I; DNA polymerase II; DNA polymerase III; DNA polymerase alpha; DNA polymerase beta; DNA polymerase gamma; DNA nucleotidyltransferase (DNA-directed); deoxyribonucleate nucleotidyltransferase; deoxynucleate polymerase; deoxyribonucleic acid duplicase; deoxyribonucleic acid polymerase; deoxyribonucleic duplicase; deoxyribonucleic polymerase; deoxyribonucleic polymerase I; DNA duplicase; DNA nucleotidyltransferase; DNA polymerase; DNA replicase; DNA-dependent DNA polymerase; duplicase; Klenow fragment; sequenase; Taq DNA polymerase; Taq Pol I; Tca DNA polymerase"
        ],
        "kegg_module": [
            "M00260"
        ],
        "kegg_pathway": [
            "ko00230",
            "ko00240",
            "ko01100",
            "ko03030",
            "ko03430",
            "ko03440"
        ],
        "kegg_reaction": [
            "R00375",
            "R00376",
            "R00377",
            "R00378"
        ],
        "locus_tag": "PMM0001",
        "locus_tag_cyanorak": "CK_Pro_MED4_00001",
        "locus_tag_ncbi": "TX50_RS00020",
        "max_annot_lvl": "1117|Cyanobacteria",
        "old_locus_tags": [
            "PMM0001"
        ],
        "organism_name": "Prochlorococcus MED4",
        "ortholog_groups": [
            {
                "og_id": "cyanorak:CK_00000364",
                "source": "cyanorak",
                "specificity_rank": 0,
                "taxon_id": 0,
                "taxonomic_level": "curated"
            },
            {
                "og_id": "eggnog:COG0592@2",
                "source": "eggnog",
                "specificity_rank": 3,
                "taxon_id": 2,
                "taxonomic_level": "Bacteria"
            },
            {
                "og_id": "eggnog:1MKTR@1212",
                "source": "eggnog",
                "specificity_rank": 1,
                "taxon_id": 1212,
                "taxonomic_level": "Prochloraceae"
            },
            {
                "og_id": "eggnog:1FZV5@1117",
                "source": "eggnog",
                "specificity_rank": 2,
                "taxon_id": 1117,
                "taxonomic_level": "Cyanobacteria"
            }
        ],
        "pfam_ids": [
            "PF00712",
            "PF02768",
            "PF02767"
        ],
        "product": "DNA polymerase III, beta subunit",
        "product_cyanorak": "DNA polymerase III, beta subunit",
        "product_source": "cyanorak",
        "protein_family": "Beta sliding clamp family",
        "protein_id": "WP_011131639.1",
        "seed_ortholog": "59919.PMM0001",
        "seed_ortholog_evalue": 1.12e-267,
        "start": 174,
        "start_cyanorak": 174,
        "strand": "+",
        "strand_cyanorak": "+",
        "tIGR_Role": [
            "132"
        ],
        "tIGR_Role_description": [
            "DNA metabolism / DNA replication, recombination, and repair"
        ],
        "uniprot_accession": "Q7V3R7"
    },
    {
        "all_identifiers": [
            "CK_Pro_MED4_00002",
            "Q7V3R6",
            "TX50_RS00025",
            "WP_011131640.1"
        ],
        "alternate_functional_descriptions": [
            "[cyanorak] conserved hypothetical protein",
            "[ncbi] hypothetical protein",
            "[eggnog] Alternative locus ID",
            "[cyanorak_role] Conserved hypothetical proteins",
            "[tigr_role] Hypothetical proteins / Conserved",
            "[cog] COG: METABOLISM [C] Energy production and conversion",
            "[cog] COG: POORLY CHARACTERIZED [S] Function unknown",
            "[cog] bactNOG: POORLY CHARACTERIZED [S] Function unknown",
            "[cog] cyaNOG: POORLY CHARACTERIZED [S] Function unknown",
            "[pfam] PRC: PRC-barrel domain"
        ],
        "alternative_locus_tags": [
            "PMM0002",
            "TX50_RS00025"
        ],
        "annotation_quality": 1,
        "bacteria_cog_og": "COG3881",
        "cluster_number": "CK_00000363",
        "cog_category": [
            "S"
        ],
        "cyanorak_Role": [
            "R.2"
        ],
        "cyanorak_Role_description": [
            "Conserved hypothetical proteins"
        ],
        "eggnog_og_descriptions": [
            "COG: METABOLISM [C] Energy production and conversion",
            "COG: POORLY CHARACTERIZED [S] Function unknown",
            "bactNOG: POORLY CHARACTERIZED [S] Function unknown",
            "cyaNOG: POORLY CHARACTERIZED [S] Function unknown"
        ],
        "eggnog_ogs": [
            "COG0243",
            "NOG45784",
            "NOG237203",
            "bactNOG55577",
            "bactNOG31844",
            "cyaNOG05837",
            "cyaNOG03657",
            "COG3881@1|root",
            "COG3881@2|Bacteria",
            "1GBH7@1117|Cyanobacteria",
            "1MMB0@1212|Prochloraceae"
        ],
        "end": 2040,
        "end_cyanorak": 2040,
        "function_description": "Alternative locus ID",
        "function_description_source": "eggnog",
        "gene_category": "Unknown",
        "gene_summary": "conserved hypothetical protein :: Alternative locus ID",
        "gene_synonyms": [
            "PMM0002",
            "TX50_RS00025"
        ],
        "locus_tag": "PMM0002",
        "locus_tag_cyanorak": "CK_Pro_MED4_00002",
        "locus_tag_ncbi": "TX50_RS00025",
        "max_annot_lvl": "1117|Cyanobacteria",
        "old_locus_tags": [
            "PMM0002"
        ],
        "organism_name": "Prochlorococcus MED4",
        "ortholog_groups": [
            {
                "og_id": "cyanorak:CK_00000363",
                "source": "cyanorak",
                "specificity_rank": 0,
                "taxon_id": 0,
                "taxonomic_level": "curated"
            },
            {
                "og_id": "eggnog:COG3881@2",
                "source": "eggnog",
                "specificity_rank": 3,
                "taxon_id": 2,
                "taxonomic_level": "Bacteria"
            },
            {
                "og_id": "eggnog:1MMB0@1212",
                "source": "eggnog",
                "specificity_rank": 1,
                "taxon_id": 1212,
                "taxonomic_level": "Prochloraceae"
            },
            {
                "og_id": "eggnog:1GBH7@1117",
                "source": "eggnog",
                "specificity_rank": 2,
                "taxon_id": 1117,
                "taxonomic_level": "Cyanobacteria"
            }
        ],
        "pfam_ids": [
            "PF05239"
        ],
        "product": "conserved hypothetical protein",
        "product_cyanorak": "conserved hypothetical protein",
        "product_source": "cyanorak",
        "protein_id": "WP_011131640.1",
        "seed_ortholog": "59919.PMM0002",
        "seed_ortholog_evalue": 2.32e-171,
        "start": 1333,
        "start_cyanorak": 1333,
        "strand": "+",
        "strand_cyanorak": "+",
        "tIGR_Role": [
            "156"
        ],
        "tIGR_Role_description": [
            "Hypothetical proteins / Conserved"
        ],
        "uniprot_accession": "Q7V3R6"
    },
    {
        "all_identifiers": [
            "(coxB)",
            "CK_Pro_MED4_00446",
            "Q7V2M9",
            "TX50_RS02400",
            "WP_011132082.1",
            "coxB",
            "ctaC"
        ],
        "alternate_functional_descriptions": [
            "[cyanorak] cytochrome c oxidase subunit II",
            "[ncbi] cytochrome c oxidase subunit II",
            "[eggnog] Subunits I and II form the functional core of the enzyme complex. Electrons originating in cytochrome c are transferred via heme a and Cu(A) to the binuclear center formed by heme a3 and Cu(B)",
            "[uniprot] Subunits I and II form the functional core of the enzyme complex. Electrons originating in cytochrome c are transferred via heme a and Cu(A) to the binuclear center formed by heme a3 and Cu(B)",
            "[protein_family] Cytochrome c oxidase subunit 2 family",
            "[cyanorak_role] Electron transport",
            "[cyanorak_role] Respiratory terminal oxidases",
            "[tigr_role] Energy metabolism / Electron transport",
            "[cog] COG: METABOLISM [C] Energy production and conversion",
            "[cog] bactNOG: METABOLISM [C] Energy production and conversion",
            "[cog] cyaNOG: METABOLISM [C] Energy production and conversion",
            "[kegg] cytochrome-c oxidase; cytochrome oxidase; cytochrome a3; cytochrome aa3; Warburg's respiratory enzyme; indophenol oxidase; indophenolase; complex IV (mitochondrial electron transport); ferrocytochrome c oxidase; NADH cytochrome c oxidase",
            "[pfam] COX2: Cytochrome C oxidase subunit II, periplasmic domain",
            "[pfam] COX2_TM: Cytochrome C oxidase subunit II, transmembrane domain"
        ],
        "alternative_locus_tags": [
            "PMM0446"
        ],
        "annotation_quality": 3,
        "bacteria_cog_og": "COG1622",
        "catalytic_activities": [
            "Reaction=4 Fe(II)-[cytochrome c] + O2 + 8 H(+)(in) = 4 Fe(III)-[cytochrome c] + 2 H2O + 4 H(+)(out); Xref=Rhea:RHEA:11436, Rhea:RHEA-COMP:10350, Rhea:RHEA-COMP:14399, ChEBI:CHEBI:15377, ChEBI:CHEBI:15378, ChEBI:CHEBI:15379, ChEBI:CHEBI:29033, ChEBI:CHEBI:29034; EC=7.1.1.9; Evidence="
        ],
        "cluster_number": "CK_00000614",
        "cog_category": [
            "C"
        ],
        "cyanorak_Role": [
            "G.2",
            "J.9"
        ],
        "cyanorak_Role_description": [
            "Electron transport",
            "Respiratory terminal oxidases"
        ],
        "ec_numbers": [
            "7.1.1.9"
        ],
        "eggnog_og_descriptions": [
            "COG: METABOLISM [C] Energy production and conversion",
            "bactNOG: METABOLISM [C] Energy production and conversion",
            "cyaNOG: METABOLISM [C] Energy production and conversion"
        ],
        "eggnog_ogs": [
            "COG1622",
            "bactNOG00399",
            "bactNOG06838",
            "bactNOG10042",
            "cyaNOG00648",
            "COG1622@1|root",
            "COG1622@2|Bacteria",
            "1G0EQ@1117|Cyanobacteria",
            "1MKMP@1212|Prochloraceae"
        ],
        "end": 425917,
        "end_cyanorak": 425917,
        "function_description": "Subunits I and II form the functional core of the enzyme complex. Electrons originating in cytochrome c are transferred via heme a and Cu(A) to the binuclear center formed by heme a3 and Cu(B)",
        "function_description_source": "uniprot",
        "gene_category": "Carbohydrate metabolism",
        "gene_name": "ctaCI",
        "gene_name_source": "cyanorak",
        "gene_name_synonyms": [
            "coxB",
            "ctaC",
            "(coxB)"
        ],
        "gene_summary": "ctaCI :: cytochrome c oxidase subunit II :: Subunits I and II form the functional core of the enzyme complex. Electrons originating in cytochrome c are transferred via heme a and Cu(A) to the binuclear center formed by heme a3 and Cu(B)",
        "gene_synonyms": [
            "coxB",
            "PMM0446",
            "ctaC",
            "(coxB)"
        ],
        "go_term_descriptions": [
            "oxidation-reduction process",
            "oxidation-reduction process",
            "cytochrome-c oxidase activity"
        ],
        "go_terms": [
            "GO:0005886",
            "GO:0042773",
            "GO:0005507",
            "GO:0004129",
            "GO:0016491",
            "GO:0016020",
            "GO:0055114",
            "GO:0005575",
            "GO:0005623",
            "GO:0005887",
            "GO:0006091",
            "GO:0006119",
            "GO:0006139",
            "GO:0006163",
            "GO:0006725",
            "GO:0006753",
            "GO:0006793",
            "GO:0006796",
            "GO:0006807",
            "GO:0008150",
            "GO:0008152",
            "GO:0009117",
            "GO:0009123",
            "GO:0009126",
            "GO:0009141",
            "GO:0009144",
            "GO:0009150",
            "GO:0009161",
            "GO:0009167",
            "GO:0009199",
            "GO:0009205",
            "GO:0009259",
            "GO:0009319",
            "GO:0009987",
            "GO:0015980",
            "GO:0016021",
            "GO:0016310",
            "GO:0017144",
            "GO:0019637",
            "GO:0019693",
            "GO:0022900",
            "GO:0022904",
            "GO:0031224",
            "GO:0031226",
            "GO:0032991",
            "GO:0034641",
            "GO:0044237",
            "GO:0044238",
            "GO:0044281",
            "GO:0044425",
            "GO:0044459",
            "GO:0044464",
            "GO:0045333",
            "GO:0046034",
            "GO:0046483",
            "GO:0055086",
            "GO:0070069",
            "GO:0071704",
            "GO:0071944",
            "GO:0072521",
            "GO:0098796",
            "GO:1901135",
            "GO:1901360",
            "GO:1901564",
            "GO:1902494"
        ],
        "kegg_brite": [
            "ko00000",
            "ko00001",
            "ko00002",
            "ko01000"
        ],
        "kegg_ko": [
            "K02275"
        ],
        "kegg_ko_descriptions": [
            "cytochrome-c oxidase; cytochrome oxidase; cytochrome a3; cytochrome aa3; Warburg's respiratory enzyme; indophenol oxidase; indophenolase; complex IV (mitochondrial electron transport); ferrocytochrome c oxidase; NADH cytochrome c oxidase"
        ],
        "kegg_module": [
            "M00155"
        ],
        "kegg_pathway": [
            "ko00190",
            "ko01100"
        ],
        "kegg_reaction": [
            "R00081"
        ],
        "locus_tag": "PMM0446",
        "locus_tag_cyanorak": "CK_Pro_MED4_00446",
        "locus_tag_ncbi": "TX50_RS02400",
        "max_annot_lvl": "1117|Cyanobacteria",
        "old_locus_tags": [
            "PMM0446"
        ],
        "organism_name": "Prochlorococcus MED4",
        "ortholog_groups": [
            {
                "og_id": "cyanorak:CK_00000614",
                "source": "cyanorak",
                "specificity_rank": 0,
                "taxon_id": 0,
                "taxonomic_level": "curated"
            },
            {
                "og_id": "eggnog:COG1622@2",
                "source": "eggnog",
                "specificity_rank": 3,
                "taxon_id": 2,
                "taxonomic_level": "Bacteria"
            },
            {
                "og_id": "eggnog:1MKMP@1212",
                "source": "eggnog",
                "specificity_rank": 1,
                "taxon_id": 1212,
                "taxonomic_level": "Prochloraceae"
            },
            {
                "og_id": "eggnog:1G0EQ@1117",
                "source": "eggnog",
                "specificity_rank": 2,
                "taxon_id": 1117,
                "taxonomic_level": "Cyanobacteria"
            }
        ],
        "pfam_ids": [
            "PF00116",
            "PF02790"
        ],
        "product": "cytochrome c oxidase subunit II",
        "product_cyanorak": "cytochrome c oxidase subunit II",
        "product_source": "cyanorak",
        "protein_family": "Cytochrome c oxidase subunit 2 family",
        "protein_id": "WP_011132082.1",
        "seed_ortholog": "59919.PMM0446",
        "seed_ortholog_evalue": 3.56e-191,
        "start": 425114,
        "start_cyanorak": 425114,
        "tIGR_Role": [
            "112"
        ],
        "tIGR_Role_description": [
            "Energy metabolism / Electron transport"
        ],
        "transmembrane_regions": [
            "7..26",
            "46..67",
            "88..108"
        ],
        "uniprot_accession": "Q7V2M9"
    },
    {
        "all_identifiers": [
            "CK_Pro_MIT9312_00001",
            "PMT9312_RS00005",
            "Q31DI3",
            "WP_011375566.1"
        ],
        "alternate_functional_descriptions": [
            "[cyanorak] DNA polymerase III, beta subunit",
            "[ncbi] DNA polymerase III subunit beta",
            "[eggnog] Confers DNA tethering and processivity to DNA polymerases and other proteins. Acts as a clamp, forming a ring around DNA (a reaction catalyzed by the clamp-loading complex) which diffuses in an ATP-independent manner freely and bidirectionally along dsDNA. Initially characterized for its ability to contact the catalytic subunit of DNA polymerase III (Pol III), a complex, multichain enzyme responsible for most of the replicative synthesis in bacteria",
            "[uniprot] Confers DNA tethering and processivity to DNA polymerases and other proteins. Acts as a clamp, forming a ring around DNA (a reaction catalyzed by the clamp-loading complex) which diffuses in an ATP-independent manner freely and bidirectionally along dsDNA. Initially characterized for its ability to contact the catalytic subunit of DNA polymerase III (Pol III), a complex, multichain enzyme responsible for most of the replicative synthesis in bacteria; Pol III exhibits 3^-5^ exonuclease proofreading activity. The beta chain is required for initiation of replication as well as for processivity of DNA replication",
            "[protein_family] Beta sliding clamp family",
            "[cyanorak_role] DNA replication, recombination, and repair",
            "[tigr_role] DNA metabolism / DNA replication, recombination, and repair",
            "[cog] COG: INFORMATION STORAGE AND PROCESSING [L] Replication, recombination and repair",
            "[cog] bactNOG: INFORMATION STORAGE AND PROCESSING [L] Replication, recombination and repair",
            "[cog] cyaNOG: INFORMATION STORAGE AND PROCESSING [L] Replication, recombination and repair",
            "[kegg] DNA-directed DNA polymerase; DNA polymerase I; DNA polymerase II; DNA polymerase III; DNA polymerase alpha; DNA polymerase beta; DNA polymerase gamma; DNA nucleotidyltransferase (DNA-directed); deoxyribonucleate nucleotidyltransferase; deoxynucleate polymerase; deoxyribonucleic acid duplicase; deoxyribonucleic acid polymerase; deoxyribonucleic duplicase; deoxyribonucleic polymerase; deoxyribonucleic polymerase I; DNA duplicase; DNA nucleotidyltransferase; DNA polymerase; DNA replicase; DNA-dependent DNA polymerase; duplicase; Klenow fragment; sequenase; Taq DNA polymerase; Taq Pol I; Tca DNA polymerase",
            "[pfam] DNA_pol3_beta: DNA polymerase III beta subunit, N-terminal domain",
            "[pfam] DNA_pol3_beta_3: DNA polymerase III beta subunit, C-terminal domain",
            "[pfam] DNA_pol3_beta_2: DNA polymerase III beta subunit, central domain"
        ],
        "alternative_locus_tags": [
            "PMT9312_0001"
        ],
        "annotation_quality": 3,
        "bacteria_cog_og": "COG0592",
        "cluster_number": "CK_00000364",
        "cog_category": [
            "L"
        ],
        "cyanorak_Role": [
            "F.1"
        ],
        "cyanorak_Role_description": [
            "DNA replication, recombination, and repair"
        ],
        "ec_numbers": [
            "2.7.7.7"
        ],
        "eggnog_og_descriptions": [
            "COG: INFORMATION STORAGE AND PROCESSING [L] Replication, recombination and repair",
            "bactNOG: INFORMATION STORAGE AND PROCESSING [L] Replication, recombination and repair",
            "cyaNOG: INFORMATION STORAGE AND PROCESSING [L] Replication, recombination and repair"
        ],
        "eggnog_ogs": [
            "COG0592",
            "bactNOG00989",
            "cyaNOG01040",
            "COG0592@1|root",
            "COG0592@2|Bacteria",
            "1FZV5@1117|Cyanobacteria",
            "1MKTR@1212|Prochloraceae"
        ],
        "end": 1362,
        "end_cyanorak": 1362,
        "function_description": "Confers DNA tethering and processivity to DNA polymerases and other proteins. Acts as a clamp, forming a ring around DNA (a reaction catalyzed by the clamp-loading complex) which diffuses in an ATP-independent manner freely and bidirectionally along dsDNA. Initially characterized for its ability to contact the catalytic subunit of DNA polymerase III (Pol III), a complex, multichain enzyme responsible for most of the replicative synthesis in bacteria; Pol III exhibits 3^-5^ exonuclease proofreading activity. The beta chain is required for initiation of replication as well as for processivity of DNA replication",
        "function_description_source": "uniprot",
        "gene_category": "Replication and repair",
        "gene_name": "dnaN",
        "gene_name_source": "cyanorak",
        "gene_summary": "dnaN :: DNA polymerase III, beta subunit :: Confers DNA tethering and processivity to DNA polymerases and other proteins. Acts as a clamp, forming a ring around DNA (a reaction catalyzed by the clamp-loading complex) which diffuses in an ATP-independent manner freely and bidirectionally along dsDNA. Initially characterized for its ability to contact the catalytic subunit of DNA polymerase III (Pol III), a complex, multichain enzyme responsible for most of the replicative synthesis in bacteria; Pol III exhibits 3^-5^ exonuclease proofreading activity. The beta chain is required for initiation of replication as well as for processivity of DNA replication",
        "gene_synonyms": [
            "PMT9312_0001"
        ],
        "go_term_descriptions": [
            "DNA replication",
            "DNA replication",
            "DNA polymerase activity",
            "DNA binding",
            "DNA-directed DNA polymerase activity",
            "3'-5' exonuclease activity",
            "DNA replication",
            "DNA polymerase activity",
            "DNA binding",
            "DNA-directed DNA polymerase activity",
            "3'-5' exonuclease activity",
            "DNA polymerase III complex"
        ],
        "go_terms": [
            "GO:0005737",
            "GO:0009360",
            "GO:0006271",
            "GO:0008408",
            "GO:0003677",
            "GO:0003887",
            "GO:0006260",
            "GO:0034061"
        ],
        "kegg_brite": [
            "ko00000",
            "ko00001",
            "ko00002",
            "ko01000",
            "ko03032",
            "ko03400"
        ],
        "kegg_ko": [
            "K02338"
        ],
        "kegg_ko_descriptions": [
            "DNA-directed DNA polymerase; DNA polymerase I; DNA polymerase II; DNA polymerase III; DNA polymerase alpha; DNA polymerase beta; DNA polymerase gamma; DNA nucleotidyltransferase (DNA-directed); deoxyribonucleate nucleotidyltransferase; deoxynucleate polymerase; deoxyribonucleic acid duplicase; deoxyribonucleic acid polymerase; deoxyribonucleic duplicase; deoxyribonucleic polymerase; deoxyribonucleic polymerase I; DNA duplicase; DNA nucleotidyltransferase; DNA polymerase; DNA replicase; DNA-dependent DNA polymerase; duplicase; Klenow fragment; sequenase; Taq DNA polymerase; Taq Pol I; Tca DNA polymerase"
        ],
        "kegg_module": [
            "M00260"
        ],
        "kegg_pathway": [
            "ko00230",
            "ko00240",
            "ko01100",
            "ko03030",
            "ko03430",
            "ko03440"
        ],
        "kegg_reaction": [
            "R00375",
            "R00376",
            "R00377",
            "R00378"
        ],
        "locus_tag": "PMT9312_0001",
        "locus_tag_cyanorak": "CK_Pro_MIT9312_00001",
        "locus_tag_ncbi": "PMT9312_RS00005",
        "max_annot_lvl": "1117|Cyanobacteria",
        "old_locus_tags": [
            "PMT9312_0001"
        ],
        "organism_name": "Prochlorococcus MIT9312",
        "ortholog_groups": [
            {
                "og_id": "cyanorak:CK_00000364",
                "source": "cyanorak",
                "specificity_rank": 0,
                "taxon_id": 0,
                "taxonomic_level": "curated"
            },
            {
                "og_id": "eggnog:COG0592@2",
                "source": "eggnog",
                "specificity_rank": 3,
                "taxon_id": 2,
                "taxonomic_level": "Bacteria"
            },
            {
                "og_id": "eggnog:1MKTR@1212",
                "source": "eggnog",
                "specificity_rank": 1,
                "taxon_id": 1212,
                "taxonomic_level": "Prochloraceae"
            },
            {
                "og_id": "eggnog:1FZV5@1117",
                "source": "eggnog",
                "specificity_rank": 2,
                "taxon_id": 1117,
                "taxonomic_level": "Cyanobacteria"
            }
        ],
        "pfam_ids": [
            "PF00712",
            "PF02768",
            "PF02767"
        ],
        "product": "DNA polymerase III, beta subunit",
        "product_cyanorak": "DNA polymerase III, beta subunit",
        "product_source": "cyanorak",
        "protein_family": "Beta sliding clamp family",
        "protein_id": "WP_011375566.1",
        "seed_ortholog": "74546.PMT9312_0001",
        "seed_ortholog_evalue": 1.66e-269,
        "start": 205,
        "start_cyanorak": 205,
        "strand": "+",
        "strand_cyanorak": "+",
        "tIGR_Role": [
            "132"
        ],
        "tIGR_Role_description": [
            "DNA metabolism / DNA replication, recombination, and repair"
        ],
        "uniprot_accession": "Q31DI3"
    },
    {
        "all_identifiers": [
            "CK_Pro_MIT9312_00342"
        ],
        "alternate_functional_descriptions": [
            "[cyanorak] hypothetical protein"
        ],
        "annotation_quality": 0,
        "cluster_number": "CK_00038231",
        "end_cyanorak": 329961,
        "gene_category": "Unknown",
        "gene_summary": "hypothetical protein",
        "locus_tag": "PMT9312_0342",
        "locus_tag_cyanorak": "CK_Pro_MIT9312_00342",
        "organism_name": "Prochlorococcus MIT9312",
        "ortholog_groups": [
            {
                "og_id": "cyanorak:CK_00038231",
                "source": "cyanorak",
                "specificity_rank": 0,
                "taxon_id": 0,
                "taxonomic_level": "curated"
            }
        ],
        "product": "hypothetical protein",
        "product_cyanorak": "hypothetical protein",
        "product_source": "cyanorak",
        "start_cyanorak": 329599
    },
    {
        "all_identifiers": [
            "CK_Pro_NATL2A_00044",
            "PMN2A_RS03160",
            "Q46LU2",
            "WP_011293578.1"
        ],
        "alternate_functional_descriptions": [
            "[cyanorak] naphthoate synthase",
            "[ncbi] 1,4-dihydroxy-2-naphthoyl-CoA synthase",
            "[eggnog] Converts o-succinylbenzoyl-CoA (OSB-CoA) to 1,4- dihydroxy-2-naphthoyl-CoA (DHNA-CoA)",
            "[uniprot] Converts o-succinylbenzoyl-CoA (OSB-CoA) to 1,4-dihydroxy-2-naphthoyl-CoA (DHNA-CoA)",
            "[protein_family] Enoyl-CoA hydratase/isomerase family, MenB subfamily",
            "[cyanorak_role] Plastoquinone, menaquinone and ubiquinone",
            "[tigr_role] Biosynthesis of cofactors, prosthetic groups, and carriers / Menaquinone and ubiquinone",
            "[cog] COG: METABOLISM [H] Coenzyme transport and metabolism",
            "[cog] bactNOG: METABOLISM [H] Coenzyme transport and metabolism",
            "[cog] bactNOG: METABOLISM [I] Lipid transport and metabolism",
            "[cog] cyaNOG: METABOLISM [H] Coenzyme transport and metabolism",
            "[kegg] 1",
            "[kegg] 4-dihydroxy-2-naphthoyl-CoA synthase; naphthoate synthase; 1",
            "[kegg] 4-dihydroxy-2-naphthoate synthase; dihydroxynaphthoate synthase; o-succinylbenzoyl-CoA 1",
            "[kegg] 4-dihydroxy-2-naphthoate-lyase (cyclizing); MenB; o-succinylbenzoyl-CoA dehydratase (cyclizing)",
            "[pfam] ECH_1: Enoyl-CoA hydratase/isomerase"
        ],
        "alternative_locus_tags": [
            "PMN2A_0044"
        ],
        "annotation_quality": 3,
        "bacteria_cog_og": "COG0447",
        "bigg_reaction": [
            "iJN678.menB"
        ],
        "catalytic_activities": [
            "Reaction=2-succinylbenzoyl-CoA + H(+) = 1,4-dihydroxy-2-naphthoyl-CoA + H2O; Xref=Rhea:RHEA:26562, ChEBI:CHEBI:15377, ChEBI:CHEBI:15378, ChEBI:CHEBI:57364, ChEBI:CHEBI:58897; EC=4.1.3.36; Evidence="
        ],
        "cluster_number": "CK_00000769",
        "cog_category": [
            "H"
        ],
        "cyanorak_Role": [
            "B.2"
        ],
        "cyanorak_Role_description": [
            "Plastoquinone, menaquinone and ubiquinone"
        ],
        "ec_numbers": [
            "4.1.3.36"
        ],
        "eggnog_og_descriptions": [
            "COG: METABOLISM [H] Coenzyme transport and metabolism",
            "bactNOG: METABOLISM [H] Coenzyme transport and metabolism",
            "bactNOG: METABOLISM [I] Lipid transport and metabolism",
            "cyaNOG: METABOLISM [H] Coenzyme transport and metabolism"
        ],
        "eggnog_ogs": [
            "COG0447",
            "bactNOG01168",
            "bactNOG00276",
            "cyaNOG01815",
            "cyaNOG06466",
            "COG0447@1|root",
            "COG0447@2|Bacteria",
            "1G10D@1117|Cyanobacteria",
            "1MKQ6@1212|Prochloraceae"
        ],
        "end": 598565,
        "end_cyanorak": 598565,
        "function_description": "Converts o-succinylbenzoyl-CoA (OSB-CoA) to 1,4-dihydroxy-2-naphthoyl-CoA (DHNA-CoA)",
        "function_description_source": "uniprot",
        "gene_category": "Coenzyme metabolism",
        "gene_name": "menB",
        "gene_name_source": "cyanorak",
        "gene_summary": "menB :: naphthoate synthase :: Converts o-succinylbenzoyl-CoA (OSB-CoA) to 1,4-dihydroxy-2-naphthoyl-CoA (DHNA-CoA)",
        "gene_synonyms": [
            "PMN2A_0044"
        ],
        "go_term_descriptions": [
            "phylloquinone biosynthetic process",
            "phylloquinone biosynthetic process",
            "1",
            "4-dihydroxy-2-naphthoyl-CoA synthase activity"
        ],
        "go_terms": [
            "GO:0005829",
            "GO:0009234",
            "GO:0042372",
            "GO:0008935"
        ],
        "kegg_brite": [
            "ko00000",
            "ko00001",
            "ko00002",
            "ko01000"
        ],
        "kegg_ko": [
            "K01661"
        ],
        "kegg_ko_descriptions": [
            "1",
            "4-dihydroxy-2-naphthoyl-CoA synthase; naphthoate synthase; 1",
            "4-dihydroxy-2-naphthoate synthase; dihydroxynaphthoate synthase; o-succinylbenzoyl-CoA 1",
            "4-dihydroxy-2-naphthoate-lyase (cyclizing); MenB; o-succinylbenzoyl-CoA dehydratase (cyclizing)"
        ],
        "kegg_module": [
            "M00116"
        ],
        "kegg_pathway": [
            "ko00130",
            "ko01100",
            "ko01110"
        ],
        "kegg_reaction": [
            "R07263"
        ],
        "locus_tag": "PMN2A_0044",
        "locus_tag_cyanorak": "CK_Pro_NATL2A_00044",
        "locus_tag_ncbi": "PMN2A_RS03160",
        "max_annot_lvl": "1117|Cyanobacteria",
        "old_locus_tags": [
            "PMN2A_0044"
        ],
        "organism_name": "Prochlorococcus NATL2A",
        "ortholog_groups": [
            {
                "og_id": "cyanorak:CK_00000769",
                "source": "cyanorak",
                "specificity_rank": 0,
                "taxon_id": 0,
                "taxonomic_level": "curated"
            },
            {
                "og_id": "eggnog:COG0447@2",
                "source": "eggnog",
                "specificity_rank": 3,
                "taxon_id": 2,
                "taxonomic_level": "Bacteria"
            },
            {
                "og_id": "eggnog:1MKQ6@1212",
                "source": "eggnog",
                "specificity_rank": 1,
                "taxon_id": 1212,
                "taxonomic_level": "Prochloraceae"
            },
            {
                "og_id": "eggnog:1G10D@1117",
                "source": "eggnog",
                "specificity_rank": 2,
                "taxon_id": 1117,
                "taxonomic_level": "Cyanobacteria"
            }
        ],
        "pfam_ids": [
            "PF00378"
        ],
        "product": "naphthoate synthase",
        "product_cyanorak": "naphthoate synthase",
        "product_source": "cyanorak",
        "protein_family": "Enoyl-CoA hydratase/isomerase family, MenB subfamily",
        "protein_id": "WP_011293578.1",
        "seed_ortholog": "167555.NATL1_06641",
        "seed_ortholog_evalue": 1.87e-213,
        "start": 597666,
        "start_cyanorak": 597666,
        "strand": "+",
        "strand_cyanorak": "+",
        "tIGR_Role": [
            "81"
        ],
        "tIGR_Role_description": [
            "Biosynthesis of cofactors, prosthetic groups, and carriers / Menaquinone and ubiquinone"
        ],
        "uniprot_accession": "Q46LU2"
    },
    {
        "all_identifiers": [
            "WP_197047964.1"
        ],
        "alternate_functional_descriptions": [
            "[ncbi] IS630 family transposase",
            "[eggnog] Winged helix-turn helix",
            "[pfam] DDE_3: DDE superfamily endonuclease",
            "[pfam] HTH_32: Homeodomain-like domain"
        ],
        "alternative_locus_tags": [
            "ALT831_RS00180"
        ],
        "annotation_quality": 3,
        "bacteria_cog_og": "COG3335",
        "cog_category": [
            "L"
        ],
        "eggnog_ogs": [
            "COG3335@1|root",
            "COG3415@1|root",
            "COG3335@2|Bacteria",
            "COG3415@2|Bacteria",
            "1RCFZ@1224|Proteobacteria",
            "1S2QS@1236|Gammaproteobacteria",
            "2QEEF@267890|Shewanellaceae"
        ],
        "end": 40258,
        "function_description": "Winged helix-turn helix",
        "function_description_source": "eggnog",
        "gene_category": "Replication and repair",
        "gene_summary": "IS630 family transposase :: Winged helix-turn helix",
        "gene_synonyms": [
            "ALT831_RS00180"
        ],
        "go_terms": [
            "GO:0004803"
        ],
        "locus_tag": "ALT831_RS00180",
        "locus_tag_ncbi": "ALT831_RS00180",
        "max_annot_lvl": "1236|Gammaproteobacteria",
        "organism_name": "Alteromonas macleodii MIT1002",
        "ortholog_groups": [
            {
                "og_id": "eggnog:COG3415@2",
                "source": "eggnog",
                "specificity_rank": 3,
                "taxon_id": 2,
                "taxonomic_level": "Bacteria"
            },
            {
                "og_id": "eggnog:1RCFZ@1224",
                "source": "eggnog",
                "specificity_rank": 2,
                "taxon_id": 1224,
                "taxonomic_level": "Proteobacteria"
            }
        ],
        "pfam_ids": [
            "PF13358",
            "PF13565"
        ],
        "product": "IS630 family transposase",
        "product_source": "ncbi",
        "protein_id": "WP_197047964.1",
        "seed_ortholog": "211586.SO_2275",
        "seed_ortholog_evalue": 9.55e-143,
        "start": 39682
    },
    {
        "all_identifiers": [
            "WP_156080631.1"
        ],
        "alternate_functional_descriptions": [
            "[ncbi] hypothetical protein"
        ],
        "alternative_locus_tags": [
            "ALT831_RS00590"
        ],
        "annotation_quality": 0,
        "end": 130720,
        "gene_category": "Unknown",
        "gene_summary": "hypothetical protein",
        "gene_synonyms": [
            "ALT831_RS00590"
        ],
        "locus_tag": "ALT831_RS00590",
        "locus_tag_ncbi": "ALT831_RS00590",
        "organism_name": "Alteromonas macleodii MIT1002",
        "product": "hypothetical protein",
        "product_source": "ncbi",
        "protein_id": "WP_156080631.1",
        "start": 130577,
        "strand": "+"
    },
    {
        "all_identifiers": [
            "WP_231514246.1"
        ],
        "alternate_functional_descriptions": [
            "[ncbi] hypothetical protein",
            "[eggnog] 5'-nucleotidase, C-terminal domain",
            "[pfam] 5_nucleotid_C: 5'-nucleotidase, C-terminal domain",
            "[pfam] Metallophos: Calcineurin-like phosphoesterase"
        ],
        "alternative_locus_tags": [
            "ALT831_RS03440"
        ],
        "alteromonadaceae_og": "46684@72275|Alteromonadaceae",
        "annotation_quality": 1,
        "bacteria_cog_og": "COG0737",
        "cog_category": [
            "F"
        ],
        "ec_numbers": [
            "3.1.3.5",
            "3.6.1.45"
        ],
        "eggnog_ogs": [
            "COG0737@1|root",
            "COG0737@2|Bacteria",
            "1MX03@1224|Proteobacteria",
            "1RPX3@1236|Gammaproteobacteria",
            "46684@72275|Alteromonadaceae"
        ],
        "end": 771889,
        "function_description": "5'-nucleotidase, C-terminal domain",
        "function_description_source": "eggnog",
        "gene_category": "Nucleotide metabolism",
        "gene_summary": "hypothetical protein :: 5'-nucleotidase, C-terminal domain",
        "gene_synonyms": [
            "ALT831_RS03440"
        ],
        "kegg_brite": [
            "ko00000",
            "ko00001",
            "ko01000"
        ],
        "kegg_ko": [
            "K11751"
        ],
        "kegg_pathway": [
            "ko00230",
            "ko00240",
            "ko00760",
            "ko01100",
            "ko01110"
        ],
        "kegg_reaction": [
            "R00183",
            "R00511",
            "R00963",
            "R01126",
            "R01227",
            "R01569",
            "R01664",
            "R01968",
            "R02088",
            "R02102",
            "R02323",
            "R02719",
            "R03346"
        ],
        "locus_tag": "ALT831_RS03440",
        "locus_tag_ncbi": "ALT831_RS03440",
        "max_annot_lvl": "1236|Gammaproteobacteria",
        "organism_name": "Alteromonas macleodii MIT1002",
        "ortholog_groups": [
            {
                "og_id": "eggnog:COG0737@2",
                "source": "eggnog",
                "specificity_rank": 3,
                "taxon_id": 2,
                "taxonomic_level": "Bacteria"
            },
            {
                "og_id": "eggnog:46684@72275",
                "source": "eggnog",
                "specificity_rank": 1,
                "taxon_id": 72275,
                "taxonomic_level": "Alteromonadaceae"
            },
            {
                "og_id": "eggnog:1MX03@1224",
                "source": "eggnog",
                "specificity_rank": 2,
                "taxon_id": 1224,
                "taxonomic_level": "Proteobacteria"
            }
        ],
        "pfam_ids": [
            "PF02872",
            "PF00149"
        ],
        "product": "hypothetical protein",
        "product_source": "ncbi",
        "protein_id": "WP_231514246.1",
        "seed_ortholog": "1004785.AMBLS11_02990",
        "seed_ortholog_evalue": 1.79e-28,
        "start": 771680,
        "strand": "+"
    },
    {
        "all_identifiers": [
            "WP_156085955.1"
        ],
        "alternate_functional_descriptions": [
            "[ncbi] YbaN family protein",
            "[eggnog] protein conserved in bacteria",
            "[pfam] DUF454: Protein of unknown function (DUF454)"
        ],
        "alternative_locus_tags": [
            "ALTBGP6_RS03775"
        ],
        "alteromonadaceae_og": "468S0@72275|Alteromonadaceae",
        "annotation_quality": 3,
        "bacteria_cog_og": "COG2832",
        "cog_category": [
            "S"
        ],
        "eggnog_ogs": [
            "COG2832@1|root",
            "COG2832@2|Bacteria",
            "1N7BI@1224|Proteobacteria",
            "1SCJZ@1236|Gammaproteobacteria",
            "468S0@72275|Alteromonadaceae"
        ],
        "end": 866085,
        "function_description": "protein conserved in bacteria",
        "function_description_source": "eggnog",
        "gene_category": "Unknown",
        "gene_name": "ybaN",
        "gene_name_source": "eggnog",
        "gene_summary": "ybaN :: YbaN family protein :: protein conserved in bacteria",
        "gene_synonyms": [
            "ALTBGP6_RS03775"
        ],
        "go_terms": [
            "GO:0005886",
            "GO:0016020",
            "GO:0005575",
            "GO:0005623",
            "GO:0044464",
            "GO:0071944"
        ],
        "kegg_brite": [
            "ko00000"
        ],
        "kegg_ko": [
            "K09790"
        ],
        "locus_tag": "ALTBGP6_RS03775",
        "locus_tag_ncbi": "ALTBGP6_RS03775",
        "max_annot_lvl": "1236|Gammaproteobacteria",
        "organism_name": "Alteromonas macleodii EZ55",
        "ortholog_groups": [
            {
                "og_id": "eggnog:COG2832@2",
                "source": "eggnog",
                "specificity_rank": 3,
                "taxon_id": 2,
                "taxonomic_level": "Bacteria"
            },
            {
                "og_id": "eggnog:468S0@72275",
                "source": "eggnog",
                "specificity_rank": 1,
                "taxon_id": 72275,
                "taxonomic_level": "Alteromonadaceae"
            },
            {
                "og_id": "eggnog:1N7BI@1224",
                "source": "eggnog",
                "specificity_rank": 2,
                "taxon_id": 1224,
                "taxonomic_level": "Proteobacteria"
            }
        ],
        "pfam_ids": [
            "PF04304"
        ],
        "product": "YbaN family protein",
        "product_source": "ncbi",
        "protein_id": "WP_156085955.1",
        "seed_ortholog": "1004785.AMBLS11_03430",
        "seed_ortholog_evalue": 1.22e-77,
        "start": 865717,
        "strand": "+"
    },
    {
        "all_identifiers": [
            "CK_Syn_WH8102_00305",
            "Q7U9F3",
            "TX72_RS01535",
            "WP_011127179.1",
            "ftsH",
            "ftsH2",
            "ftsH3"
        ],
        "alternate_functional_descriptions": [
            "[cyanorak] cell division protein FtsH1",
            "[ncbi] ATP-dependent zinc metalloprotease FtsH3",
            "[eggnog] Acts as a processive, ATP-dependent zinc metallopeptidase for both cytoplasmic and membrane proteins. Plays a role in the quality control of integral membrane proteins",
            "[uniprot] Acts as a processive, ATP-dependent zinc metallopeptidase for both cytoplasmic and membrane proteins. Plays a role in the quality control of integral membrane proteins",
            "[protein_family] AAA ATPase family; Peptidase M41 family; AAA ATPase family",
            "[cyanorak_role] Cell division",
            "[tigr_role] Cellular processes / Cell division",
            "[cog] COG: CELLULAR PROCESSES AND SIGNALING [O] Posttranslational modification, protein turnover, chaperones",
            "[cog] bactNOG: CELLULAR PROCESSES AND SIGNALING [O] Posttranslational modification, protein turnover, chaperones",
            "[cog] cyaNOG: CELLULAR PROCESSES AND SIGNALING [O] Posttranslational modification, protein turnover, chaperones",
            "[pfam] Peptidase_M41: Peptidase family M41",
            "[pfam] FtsH_ext: FtsH Extracellular",
            "[pfam] AAA: ATPase family associated with various cellular activities (AAA)",
            "[pfam] AAA_lid_3: AAA+ lid domain"
        ],
        "alternative_locus_tags": [
            "SYNW0305"
        ],
        "annotation_quality": 3,
        "bacteria_cog_og": "COG0465",
        "cluster_number": "CK_00008085",
        "cog_category": [
            "O"
        ],
        "cyanorak_Role": [
            "D.2"
        ],
        "cyanorak_Role_description": [
            "Cell division"
        ],
        "ec_numbers": [
            "3.4.24.-"
        ],
        "eggnog_og_descriptions": [
            "COG: CELLULAR PROCESSES AND SIGNALING [O] Posttranslational modification, protein turnover, chaperones",
            "bactNOG: CELLULAR PROCESSES AND SIGNALING [O] Posttranslational modification, protein turnover, chaperones",
            "cyaNOG: CELLULAR PROCESSES AND SIGNALING [O] Posttranslational modification, protein turnover, chaperones"
        ],
        "eggnog_ogs": [
            "COG0465",
            "bactNOG01729",
            "cyaNOG01610",
            "COG0465@1|root",
            "COG0465@2|Bacteria",
            "1G1BT@1117|Cyanobacteria",
            "1GYE1@1129|Synechococcus"
        ],
        "end": 304589,
        "end_cyanorak": 304589,
        "function_description": "Acts as a processive, ATP-dependent zinc metallopeptidase for both cytoplasmic and membrane proteins. Plays a role in the quality control of integral membrane proteins",
        "function_description_source": "uniprot",
        "gene_category": "Cell cycle and division",
        "gene_name": "ftsH1",
        "gene_name_source": "cyanorak",
        "gene_name_synonyms": [
            "ftsH3",
            "ftsH2",
            "ftsH"
        ],
        "gene_summary": "ftsH1 :: cell division protein FtsH1 :: Acts as a processive, ATP-dependent zinc metallopeptidase for both cytoplasmic and membrane proteins. Plays a role in the quality control of integral membrane proteins",
        "gene_synonyms": [
            "ftsH3",
            "SYNW0305",
            "ftsH2",
            "ftsH"
        ],
        "go_term_descriptions": [
            "protein catabolic process",
            "proteolysis",
            "protein catabolic process",
            "proteolysis",
            "metalloendopeptidase activity",
            "ATP binding",
            "nucleoside-triphosphatase activity",
            "zinc ion binding",
            "protein catabolic process",
            "proteolysis",
            "metalloendopeptidase activity",
            "ATP binding",
            "nucleoside-triphosphatase activity",
            "zinc ion binding",
            "thylakoid membrane",
            "integral component of membrane"
        ],
        "go_terms": [
            "GO:0031676",
            "GO:0051301",
            "GO:0030163",
            "GO:0006508",
            "GO:0005524",
            "GO:0016887",
            "GO:0004176",
            "GO:0004222",
            "GO:0008270",
            "GO:0017111",
            "GO:0042651",
            "GO:0016021",
            "GO:0003674",
            "GO:0003824",
            "GO:0006091",
            "GO:0006807",
            "GO:0008150",
            "GO:0008152",
            "GO:0008233",
            "GO:0008237",
            "GO:0009056",
            "GO:0009057",
            "GO:0009314",
            "GO:0009416",
            "GO:0009628",
            "GO:0009642",
            "GO:0009644",
            "GO:0009765",
            "GO:0009892",
            "GO:0009987",
            "GO:0010109",
            "GO:0010205",
            "GO:0010206",
            "GO:0010304",
            "GO:0015979",
            "GO:0016462",
            "GO:0016787",
            "GO:0016817",
            "GO:0016818",
            "GO:0019222",
            "GO:0019538",
            "GO:0019684",
            "GO:0030091",
            "GO:0031323",
            "GO:0031324",
            "GO:0042548",
            "GO:0042623",
            "GO:0043155",
            "GO:0043170",
            "GO:0043467",
            "GO:0044237",
            "GO:0044238",
            "GO:0044248",
            "GO:0044257",
            "GO:0044260",
            "GO:0044265",
            "GO:0044267",
            "GO:0048519",
            "GO:0048523",
            "GO:0050789",
            "GO:0050794",
            "GO:0050896",
            "GO:0065007",
            "GO:0070011",
            "GO:0071704",
            "GO:0140096",
            "GO:1901564",
            "GO:1901565",
            "GO:1901575",
            "GO:1905156"
        ],
        "kegg_brite": [
            "ko00000",
            "ko00002",
            "ko01000",
            "ko01002",
            "ko03110"
        ],
        "kegg_ko": [
            "K03798"
        ],
        "kegg_module": [
            "M00742"
        ],
        "locus_tag": "SYNW0305",
        "locus_tag_cyanorak": "CK_Syn_WH8102_00305",
        "locus_tag_ncbi": "TX72_RS01535",
        "max_annot_lvl": "1117|Cyanobacteria",
        "old_locus_tags": [
            "SYNW0305"
        ],
        "organism_name": "Synechococcus WH8102",
        "ortholog_groups": [
            {
                "og_id": "cyanorak:CK_00008085",
                "source": "cyanorak",
                "specificity_rank": 0,
                "taxon_id": 0,
                "taxonomic_level": "curated"
            },
            {
                "og_id": "eggnog:COG0465@2",
                "source": "eggnog",
                "specificity_rank": 3,
                "taxon_id": 2,
                "taxonomic_level": "Bacteria"
            },
            {
                "og_id": "eggnog:1GYE1@1129",
                "source": "eggnog",
                "specificity_rank": 1,
                "taxon_id": 1129,
                "taxonomic_level": "Synechococcus"
            },
            {
                "og_id": "eggnog:1G1BT@1117",
                "source": "eggnog",
                "specificity_rank": 2,
                "taxon_id": 1117,
                "taxonomic_level": "Cyanobacteria"
            }
        ],
        "pfam_ids": [
            "PF01434",
            "PF06480",
            "PF00004",
            "PF17862"
        ],
        "product": "cell division protein FtsH1",
        "product_cyanorak": "cell division protein FtsH1",
        "product_source": "cyanorak",
        "protein_family": "AAA ATPase family; Peptidase M41 family; AAA ATPase family",
        "protein_id": "WP_011127179.1",
        "seed_ortholog": "84588.SYNW0305",
        "seed_ortholog_evalue": 0.0,
        "start": 302742,
        "start_cyanorak": 302742,
        "strand": "+",
        "strand_cyanorak": "+",
        "tIGR_Role": [
            "93"
        ],
        "tIGR_Role_description": [
            "Cellular processes / Cell division"
        ],
        "uniprot_accession": "Q7U9F3"
    },
    {
        "all_identifiers": [
            "CK_Syn_WH8102_04001"
        ],
        "alternate_functional_descriptions": [
            "[cyanorak] putative membrane protein",
            "[tigr_role] Cell envelope / Other"
        ],
        "annotation_quality": 2,
        "cluster_number": "CK_00056274",
        "end_cyanorak": 373534,
        "gene_category": "Cell wall and membrane",
        "gene_summary": "putative membrane protein",
        "go_term_descriptions": [
            "membrane"
        ],
        "go_terms": [
            "GO:0016020"
        ],
        "locus_tag": "S8102_04001",
        "locus_tag_cyanorak": "CK_Syn_WH8102_04001",
        "organism_name": "Synechococcus WH8102",
        "ortholog_groups": [
            {
                "og_id": "cyanorak:CK_00056274",
                "source": "cyanorak",
                "specificity_rank": 0,
                "taxon_id": 0,
                "taxonomic_level": "curated"
            }
        ],
        "product": "putative membrane protein",
        "product_cyanorak": "putative membrane protein",
        "product_source": "cyanorak",
        "start_cyanorak": 373430,
        "tIGR_Role": [
            "88"
        ],
        "tIGR_Role_description": [
            "Cell envelope / Other"
        ]
    },
    {
        "all_identifiers": [
            "WP_041426808.1"
        ],
        "alternate_functional_descriptions": [
            "[ncbi] molybdenum cofactor biosynthesis protein B",
            "[eggnog] May be involved in the biosynthesis of molybdopterin",
            "[pfam] MoCF_biosynth: Probable molybdopterin binding domain"
        ],
        "annotation_quality": 3,
        "bacteria_cog_og": "COG0521",
        "cog_category": [
            "H"
        ],
        "ec_numbers": [
            "2.7.7.75"
        ],
        "eggnog_ogs": [
            "COG0521@1|root",
            "COG0521@2|Bacteria",
            "1G514@1117|Cyanobacteria",
            "1H08Z@1129|Synechococcus"
        ],
        "end": 2548880,
        "function_description": "May be involved in the biosynthesis of molybdopterin",
        "function_description_source": "eggnog",
        "gene_category": "Coenzyme metabolism",
        "gene_name": "moaB",
        "gene_name_source": "ncbi",
        "gene_summary": "moaB :: molybdenum cofactor biosynthesis protein B :: May be involved in the biosynthesis of molybdopterin",
        "go_terms": [
            "GO:0003824",
            "GO:0006777"
        ],
        "kegg_brite": [
            "ko00000",
            "ko00001",
            "ko01000"
        ],
        "kegg_ko": [
            "K03638",
            "K03831"
        ],
        "kegg_pathway": [
            "ko00790",
            "ko01100",
            "ko04122"
        ],
        "kegg_reaction": [
            "R09726"
        ],
        "locus_tag": "SYNC_RS13265",
        "locus_tag_ncbi": "SYNC_RS13265",
        "max_annot_lvl": "1117|Cyanobacteria",
        "organism_name": "Synechococcus CC9311",
        "ortholog_groups": [
            {
                "og_id": "eggnog:COG0521@2",
                "source": "eggnog",
                "specificity_rank": 3,
                "taxon_id": 2,
                "taxonomic_level": "Bacteria"
            },
            {
                "og_id": "eggnog:1H08Z@1129",
                "source": "eggnog",
                "specificity_rank": 1,
                "taxon_id": 1129,
                "taxonomic_level": "Synechococcus"
            },
            {
                "og_id": "eggnog:1G514@1117",
                "source": "eggnog",
                "specificity_rank": 2,
                "taxon_id": 1117,
                "taxonomic_level": "Cyanobacteria"
            }
        ],
        "pfam_ids": [
            "PF00994"
        ],
        "product": "molybdenum cofactor biosynthesis protein B",
        "product_source": "ncbi",
        "protein_id": "WP_041426808.1",
        "seed_ortholog": "166318.Syn8016DRAFT_2110",
        "seed_ortholog_evalue": 6.81e-115,
        "start": 2548350,
        "strand": "+"
    },
    {
        "all_identifiers": [
            "CK_Pro_MED4_00630",
            "GSTO1",
            "GSTTLp28",
            "P28",
            "Q7V256",
            "TX50_RS03345",
            "WP_011132264.1"
        ],
        "alternate_functional_descriptions": [
            "[cyanorak] glutathione S-transferase",
            "[ncbi] glutathione S-transferase",
            "[eggnog] Glutathione S-transferase",
            "[cyanorak_role] Thioredoxin, glutaredoxin and glutathione",
            "[tigr_role] Biosynthesis of cofactors, prosthetic groups, and carriers / Glutathione and analogs",
            "[cog] COG: CELLULAR PROCESSES AND SIGNALING [O] Posttranslational modification, protein turnover, chaperones",
            "[cog] COG: POORLY CHARACTERIZED [S] Function unknown",
            "[cog] bactNOG: POORLY CHARACTERIZED [S] Function unknown",
            "[cog] bactNOG: CELLULAR PROCESSES AND SIGNALING [O] Posttranslational modification, protein turnover, chaperones",
            "[cog] cyaNOG: POORLY CHARACTERIZED [S] Function unknown",
            "[kegg] glutathione transferase; glutathione S-transferase; glutathione S-alkyltransferase; glutathione S-aryltransferase; S-(hydroxyalkyl)glutathione lyase; glutathione S-aralkyltransferase; glutathione S-alkyl transferase; GST",
            "[pfam] DUF952: Protein of unknown function (DUF952)",
            "[pfam] GST_N_3: Glutathione S-transferase, N-terminal domain",
            "[pfam] GST_C_2: Glutathione S-transferase, C-terminal domain"
        ],
        "alternative_locus_tags": [
            "TX50_RS03345",
            "PMM0630"
        ],
        "annotation_quality": 3,
        "bacteria_cog_og": "COG0625",
        "cluster_number": "CK_00000753",
        "cog_category": [
            "O"
        ],
        "cyanorak_Role": [
            "B.9"
        ],
        "cyanorak_Role_description": [
            "Thioredoxin, glutaredoxin and glutathione"
        ],
        "ec_numbers": [
            "2.5.1.18"
        ],
        "eggnog_og_descriptions": [
            "COG: CELLULAR PROCESSES AND SIGNALING [O] Posttranslational modification, protein turnover, chaperones",
            "COG: POORLY CHARACTERIZED [S] Function unknown",
            "bactNOG: POORLY CHARACTERIZED [S] Function unknown",
            "bactNOG: CELLULAR PROCESSES AND SIGNALING [O] Posttranslational modification, protein turnover, chaperones",
            "cyaNOG: POORLY CHARACTERIZED [S] Function unknown"
        ],
        "eggnog_ogs": [
            "COG0625",
            "COG3502",
            "NOG245192",
            "NOG295331",
            "bactNOG28984",
            "bactNOG20861",
            "cyaNOG03537",
            "cyaNOG04378",
            "COG0625@1|root",
            "COG0625@2|Bacteria",
            "1G4IV@1117|Cyanobacteria",
            "1MMEX@1212|Prochloraceae"
        ],
        "end": 600181,
        "end_cyanorak": 600181,
        "function_description": "Glutathione S-transferase",
        "function_description_source": "eggnog",
        "gene_category": "Coenzyme metabolism",
        "gene_name": "gst",
        "gene_name_source": "cyanorak",
        "gene_name_synonyms": [
            "GSTTLp28",
            "P28",
            "GSTO1"
        ],
        "gene_summary": "gst :: glutathione S-transferase :: Glutathione S-transferase",
        "gene_synonyms": [
            "TX50_RS03345",
            "PMM0630",
            "GSTTLp28",
            "P28",
            "GSTO1"
        ],
        "go_term_descriptions": [
            "glutathione transferase activity"
        ],
        "go_terms": [
            "GO:0005737",
            "GO:0004364"
        ],
        "kegg_brite": [
            "ko00000",
            "ko00001",
            "ko01000",
            "ko02000"
        ],
        "kegg_ko": [
            "K00799"
        ],
        "kegg_ko_descriptions": [
            "glutathione transferase; glutathione S-transferase; glutathione S-alkyltransferase; glutathione S-aryltransferase; S-(hydroxyalkyl)glutathione lyase; glutathione S-aralkyltransferase; glutathione S-alkyl transferase; GST"
        ],
        "kegg_pathway": [
            "ko00480",
            "ko00980",
            "ko00982",
            "ko00983",
            "ko01524",
            "ko05200",
            "ko05204",
            "ko05225",
            "ko05418"
        ],
        "kegg_reaction": [
            "R03522",
            "R07002",
            "R07003",
            "R07004",
            "R07023",
            "R07024",
            "R07025",
            "R07026",
            "R07069",
            "R07070",
            "R07083",
            "R07084",
            "R07091",
            "R07092",
            "R07093",
            "R07094",
            "R07100",
            "R07113",
            "R07116",
            "R08280",
            "R09409",
            "R11905"
        ],
        "locus_tag": "PMM0630",
        "locus_tag_cyanorak": "CK_Pro_MED4_00630",
        "locus_tag_ncbi": "TX50_RS03345",
        "max_annot_lvl": "1117|Cyanobacteria",
        "old_locus_tags": [
            "PMM0630"
        ],
        "organism_name": "Prochlorococcus MED4",
        "ortholog_groups": [
            {
                "og_id": "cyanorak:CK_00000753",
                "source": "cyanorak",
                "specificity_rank": 0,
                "taxon_id": 0,
                "taxonomic_level": "curated"
            },
            {
                "og_id": "eggnog:COG0625@2",
                "source": "eggnog",
                "specificity_rank": 3,
                "taxon_id": 2,
                "taxonomic_level": "Bacteria"
            },
            {
                "og_id": "eggnog:1MMEX@1212",
                "source": "eggnog",
                "specificity_rank": 1,
                "taxon_id": 1212,
                "taxonomic_level": "Prochloraceae"
            },
            {
                "og_id": "eggnog:1G4IV@1117",
                "source": "eggnog",
                "specificity_rank": 2,
                "taxon_id": 1117,
                "taxonomic_level": "Cyanobacteria"
            }
        ],
        "pfam_ids": [
            "PF06108",
            "PF13417",
            "PF13410"
        ],
        "product": "glutathione S-transferase",
        "product_cyanorak": "glutathione S-transferase",
        "product_source": "cyanorak",
        "protein_id": "WP_011132264.1",
        "seed_ortholog": "59919.PMM0630",
        "seed_ortholog_evalue": 8.13e-164,
        "start": 599522,
        "start_cyanorak": 599522,
        "tIGR_Role": [
            "86"
        ],
        "tIGR_Role_description": [
            "Biosynthesis of cofactors, prosthetic groups, and carriers / Glutathione and analogs"
        ],
        "uniprot_accession": "Q7V256"
    },
    {
        "all_identifiers": [
            "WP_231506509.1"
        ],
        "alternate_functional_descriptions": [
            "[ncbi] cysteine hydrolase family protein",
            "[eggnog] Isochorismatase family",
            "[pfam] Isochorismatase: Isochorismatase domain"
        ],
        "alternative_locus_tags": [
            "ALTBGP6_RS12485"
        ],
        "annotation_quality": 3,
        "bacteria_cog_og": "COG1335",
        "cog_category": [
            "Q"
        ],
        "ec_numbers": [
            "3.-.-.-"
        ],
        "eggnog_ogs": [
            "COG1335@1|root",
            "COG1335@2|Bacteria",
            "1RDHA@1224|Proteobacteria",
            "1S6WV@1236|Gammaproteobacteria",
            "1XX0V@135623|Vibrionales"
        ],
        "end": 2861235,
        "function_description": "Isochorismatase family",
        "function_description_source": "eggnog",
        "gene_category": "Secondary metabolites",
        "gene_summary": "cysteine hydrolase family protein :: Isochorismatase family",
        "gene_synonyms": [
            "ALTBGP6_RS12485"
        ],
        "go_terms": [
            "GO:0016787"
        ],
        "locus_tag": "ALTBGP6_RS12485",
        "locus_tag_ncbi": "ALTBGP6_RS12485",
        "max_annot_lvl": "135623|Vibrionales",
        "organism_name": "Alteromonas macleodii EZ55",
        "ortholog_groups": [
            {
                "og_id": "eggnog:COG1335@2",
                "source": "eggnog",
                "specificity_rank": 3,
                "taxon_id": 2,
                "taxonomic_level": "Bacteria"
            },
            {
                "og_id": "eggnog:1RDHA@1224",
                "source": "eggnog",
                "specificity_rank": 2,
                "taxon_id": 1224,
                "taxonomic_level": "Proteobacteria"
            }
        ],
        "pfam_ids": [
            "PF00857"
        ],
        "product": "cysteine hydrolase family protein",
        "product_source": "ncbi",
        "protein_id": "WP_231506509.1",
        "seed_ortholog": "223926.28806986",
        "seed_ortholog_evalue": 1.02e-12,
        "start": 2861035,
        "strand": "+"
    },
]


# Indexes for convenient access
GENES_BY_LOCUS = {g["locus_tag"]: g for g in GENES}

# Categorized subsets
GENES_WITH_GENE_NAME = [g for g in GENES if g.get("gene_name") and g["gene_name"] != g["locus_tag"]]
GENES_WITHOUT_GENE_NAME = [g for g in GENES if not g.get("gene_name") or g["gene_name"] == g["locus_tag"]]
GENES_WITH_EC = [g for g in GENES if g.get("ec_numbers")]
GENES_HYPOTHETICAL = [g for g in GENES if "hypothetical" in g.get("product", "").lower()]


# Helper: project to resolve_gene return shape
def as_resolve_gene_result(gene):
    return {
        "locus_tag": gene["locus_tag"],
        "gene_name": gene.get("gene_name"),
        "product": gene.get("product"),
        "organism_name": gene.get("organism_name"),
    }


# Helper: project to search_genes return shape
def as_search_genes_result(gene, score=1.0):
    return {
        "locus_tag": gene["locus_tag"],
        "gene_name": gene.get("gene_name"),
        "product": gene.get("product"),
        "function_description": gene.get("function_description"),
        "gene_summary": gene.get("gene_summary"),
        "organism_name": gene.get("organism_name"),
        "annotation_quality": gene.get("annotation_quality"),
        "score": score,
    }


# Filter helpers
def genes_by_organism(organism_substring):
    return [g for g in GENES if organism_substring in g.get("organism_name", "")]


def genes_with_property(prop):
    return [g for g in GENES if g.get(prop)]


def genes_without_property(prop):
    return [g for g in GENES if not g.get(prop)]
