"""Mechanical doc-drift lints promoted from the 2026-08 MCP docs review.

Each test encodes one audit that used to be run by hand:

- ``test_docs_links_resolve``       every ``docs://`` URI / ``references/`` path /
                                    relative markdown link resolves against what
                                    server.py actually serves.
- ``test_no_stale_identifiers``     retired identifiers listed in
                                    ``inputs/lint/stale_identifiers.yaml`` do not
                                    appear in user-facing text.
- ``test_vocab_values_in_docs``     every controlled-vocabulary value quoted next
                                    to ``treatment_type`` / ``background_factors``
                                    / ``compartment`` is a live value (offline
                                    snapshot ``inputs/lint/vocab_snapshot.yaml``,
                                    regenerated by ``scripts/snapshot_vocab.py``).
- ``test_kg_claims_used_in_exist``  every ``used_in`` path in
                                    ``inputs/lint/kg_claims.yaml`` exists (the
                                    live evaluation is the ``-m kg`` test in
                                    tests/integration/test_docs_kg_claims.py).
- ``test_claude_md_table_*``        CLAUDE.md tool-table rows stay routing
                                    summaries, not changelog entries.
- ``test_tool_inventory_*``         the tool set is identical across the
                                    registry, docs, YAML, CLAUDE.md, start_here
                                    and the "N tools" claims.

No Neo4j needed. Scanned file set is shared (``DOC_FILES``) so a new surface
only needs adding in one place.
"""

from __future__ import annotations

import ast
import re
from fnmatch import fnmatch
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parents[2]
PKG = REPO / "multiomics_explorer"
REFS = PKG / "skills" / "multiomics-kg-guide" / "references"
INPUTS = PKG / "inputs"
LINT_DIR = INPUTS / "lint"
TOOLS_PY = PKG / "mcp_server" / "tools.py"
SERVER_PY = PKG / "mcp_server" / "server.py"
CLAUDE_MD = REPO / "CLAUDE.md"
EXAMPLES_DIR = REPO / "examples"
START_HERE = REFS / "guide" / "start_here.md"

DOC_FILES: list[Path] = sorted(
    list(REFS.rglob("*.md"))
    + list((INPUTS / "tools").rglob("*.yaml"))
    + list((INPUTS / "ontologies").rglob("*.yaml"))
    + [TOOLS_PY, SERVER_PY, CLAUDE_MD, EXAMPLES_DIR / "README.md"]
    + sorted(EXAMPLES_DIR.glob("*.py"))
)


def _rel(p: Path) -> str:
    return str(p.relative_to(REPO))


def _lines(p: Path) -> list[str]:
    return p.read_text(encoding="utf-8").splitlines()


# ---------------------------------------------------------------------------
# Registry helpers (derived, never hard-coded)
# ---------------------------------------------------------------------------

_TOOL_DECORATOR_RE = re.compile(
    r"@mcp\.tool\((?:[^()]|\([^()]*\))*\)\s*\n\s*(?:async )?def (\w+)\("
)


def registered_tool_names() -> set[str]:
    """Tool function names from ``@mcp.tool(...)`` decorators in tools.py.

    Regex over source (not a FastMCP import) so the lint stays cheap and
    independent of the server lifespan.
    """
    return set(_TOOL_DECORATOR_RE.findall(TOOLS_PY.read_text(encoding="utf-8")))


def served_doc_uris() -> set[str]:
    """Every ``docs://`` URI server.py serves, derived from its own registration
    code: the ``_DOC_DIRS`` globs plus the hard-coded examples list.

    Parsed from source (AST) rather than imported so the test does not build a
    FastMCP app; registering a new example in server.py makes it resolvable
    here automatically.
    """
    tree = ast.parse(SERVER_PY.read_text(encoding="utf-8"))
    uris: set[str] = set()
    doc_dirs: dict[str, str] = {}
    for node in ast.walk(tree):
        # _DOC_DIRS = {"docs://tools": (_SKILLS_DIR / "tools", ...), ...}
        if (
            isinstance(node, ast.Assign)
            and any(isinstance(t, ast.Name) and t.id == "_DOC_DIRS" for t in node.targets)
            and isinstance(node.value, ast.Dict)
        ):
            for k, v in zip(node.value.keys, node.value.values):
                prefix = ast.literal_eval(k)
                # value is a tuple; first element is `_SKILLS_DIR / "<sub>"`
                sub = v.elts[0].right if isinstance(v, ast.Tuple) else None
                doc_dirs[prefix] = ast.literal_eval(sub)
        # `for example_name, example_description in [("x.py", "..."), ...]:`
        if isinstance(node, ast.For) and isinstance(node.iter, ast.List):
            for elt in node.iter.elts:
                if isinstance(elt, ast.Tuple) and elt.elts:
                    try:
                        name = ast.literal_eval(elt.elts[0])
                    except ValueError:
                        continue
                    if isinstance(name, str) and name.endswith(".py"):
                        uris.add(f"docs://examples/{name}")
    assert doc_dirs, "could not parse _DOC_DIRS from server.py"
    for prefix, sub in doc_dirs.items():
        for md in (REFS / sub).glob("*.md"):
            uris.add(f"{prefix}/{md.stem}")
    return uris


def claude_md_rows() -> dict[str, str]:
    """``{tool_name: row_body}`` for every row of the CLAUDE.md tool table."""
    rows = {}
    for line in _lines(CLAUDE_MD):
        m = re.match(r"^\| `(\w+)` \|(.*)\|\s*$", line)
        if m:
            rows[m.group(1)] = m.group(2).strip()
    return rows


# ---------------------------------------------------------------------------
# 1. Links resolve
# ---------------------------------------------------------------------------

_DOCS_URI_RE = re.compile(r"docs://[\w/{}.\-*]+")
_REFS_PATH_RE = re.compile(r"references/[\w/.\-]+")
_MD_LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)\s]+)\)")
_TRAILING = ".,;:)`'\"*"


@pytest.mark.parametrize("path", DOC_FILES, ids=_rel)
def test_docs_links_resolve(path: Path):
    served = served_doc_uris()
    prefixes = {u.rsplit("/", 1)[0] for u in served}
    bad = []
    for i, line in enumerate(_lines(path), 1):
        for u in _DOCS_URI_RE.findall(line):
            u = u.rstrip(_TRAILING)
            if "{" in u or "*" in u:  # templated / glob form: docs://tools/{name}, docs://analysis/*
                continue
            if u.endswith("/") and u[:-1] in prefixes:  # "docs://analysis/ pages"
                continue
            if path == SERVER_PY and u in prefixes:  # the _DOC_DIRS registration keys themselves
                continue
            if u not in served:
                bad.append(f"{i}: unresolved doc URI {u}")
        for u in _REFS_PATH_RE.findall(line):
            u = u.rstrip(_TRAILING)
            if "{" in u or "*" in u:
                continue
            candidate = REFS.parent / u
            if not candidate.exists() and not (REFS / u[len("references/"):]).exists():
                bad.append(f"{i}: unresolved references/ path {u}")
        if path.suffix == ".md":
            for _txt, u in _MD_LINK_RE.findall(line):
                if u.startswith(("http://", "https://", "docs://", "#", "mailto:")):
                    continue
                if "/" not in u and "." not in u:  # `[C@H](O)` in a SMILES string is not a link
                    continue
                target = (path.parent / u.split("#", 1)[0]).resolve()
                if not target.exists():
                    bad.append(f"{i}: broken relative link {u}")
    assert not bad, f"{_rel(path)}:\n  " + "\n  ".join(bad)


# ---------------------------------------------------------------------------
# 2. Stale identifiers
# ---------------------------------------------------------------------------

def _load_stale_rules() -> list[dict]:
    rules = yaml.safe_load((LINT_DIR / "stale_identifiers.yaml").read_text(encoding="utf-8"))
    assert isinstance(rules, list) and rules
    for r in rules:
        assert {"pattern", "reason", "replacement"} <= set(r), r
        r["_re"] = re.compile(r["pattern"])
        r["_allow_in"] = re.compile(r["allow_in"]) if r.get("allow_in") else None
        r["_near"] = re.compile(r["near"]) if r.get("near") else None
    return rules


def _stale_hits(path: Path, rules: list[dict]) -> list[str]:
    rel = _rel(path)
    lines = _lines(path)
    hits = []
    for rule in rules:
        if any(fnmatch(rel, g) for g in rule.get("allow_files", []) or []):
            continue
        window = int(rule.get("near_lines", 3))
        for i, line in enumerate(lines):
            if not rule["_re"].search(line):
                continue
            if rule["_allow_in"] and rule["_allow_in"].search(line):
                continue
            if rule["_near"]:
                ctx = "\n".join(lines[max(0, i - window): i + window + 1])
                if not rule["_near"].search(ctx):
                    continue
            hits.append(
                f"{i + 1}: /{rule['pattern']}/ — {rule['reason']}; "
                f"use: {rule['replacement']}\n      {line.strip()[:140]}"
            )
    return hits


def test_stale_rules_file_is_well_formed():
    rules = _load_stale_rules()
    assert len({r["pattern"] for r in rules}) == len(rules), "duplicate pattern"


@pytest.mark.parametrize("path", DOC_FILES, ids=_rel)
def test_no_stale_identifiers(path: Path):
    hits = _stale_hits(path, _load_stale_rules())
    assert not hits, f"{_rel(path)}: stale identifiers\n  " + "\n  ".join(hits)


# ---------------------------------------------------------------------------
# 3. Vocabulary values quoted in docs are live
# ---------------------------------------------------------------------------

# Docs-side context keyword -> snapshot property. Both `treatment_type` and
# `treatment_types` (gene_response_profile) map to the same vocabulary.
_VOCAB_CONTEXTS = {
    "treatment[_ ]types?": "treatment_type",
    "background[_ ]factors": "background_factors",
    "compartments?": "compartment",
}
# `kw=['a', 'b']`, `kw: "a"`, `kw (e.g. ['a', 'b'])`, `kw="a"`
_VOCAB_ASSIGN_RE = (
    r"\b(?P<kw>{kw})\b[^\n]{{0,60}}?"
    r"(?:[:=]|\(e\.g\.|e\.g\.)\s*(?P<val>\[[^\]\n]*\]|['\"][a-z_]+['\"])"
)
_IN_TREATMENT_RE = re.compile(r"['\"]([a-z_]+)['\"]\s+IN\s+\w+\.(treatment_type|background_factors)\b")
_QUOTED_RE = re.compile(r"['\"]([a-z_]+)['\"]")
# Documentation placeholders, not values: `'value' IN e.treatment_type`.
_VOCAB_PLACEHOLDERS = {
    "value", "values",
    # kg_schema payloads render property TYPES in the same "key": "type" shape
    "list", "string", "integer", "float", "boolean", "str", "int", "bool", "array", "object", "null",
}


def _load_vocab_snapshot() -> dict[str, set[str]]:
    snap = yaml.safe_load((LINT_DIR / "vocab_snapshot.yaml").read_text(encoding="utf-8"))
    out: dict[str, set[str]] = {}
    for prop, by_applies in snap["vocabularies"].items():
        out[prop] = set().union(*(set(v["values"]) for v in by_applies.values()))
    return out


def _vocab_hits(path: Path, vocab: dict[str, set[str]]) -> list[str]:
    hits = []
    for i, line in enumerate(_lines(path), 1):
        for kw_re, prop in _VOCAB_CONTEXTS.items():
            for m in re.finditer(_VOCAB_ASSIGN_RE.format(kw=kw_re), line):
                for val in _QUOTED_RE.findall(m.group("val")):
                    if val not in vocab[prop] and val not in _VOCAB_PLACEHOLDERS:
                        hits.append(f"{i}: {prop}={val!r} is not a live value\n      {line.strip()[:140]}")
        for val, prop in _IN_TREATMENT_RE.findall(line):
            if val not in vocab[prop] and val not in _VOCAB_PLACEHOLDERS:
                hits.append(f"{i}: {prop}={val!r} is not a live value\n      {line.strip()[:140]}")
    return hits


def test_vocab_snapshot_is_well_formed():
    vocab = _load_vocab_snapshot()
    for prop in ("treatment_type", "background_factors", "compartment"):
        assert vocab.get(prop), f"snapshot lacks {prop} — run scripts/snapshot_vocab.py"


@pytest.mark.parametrize("path", DOC_FILES, ids=_rel)
def test_vocab_values_in_docs(path: Path):
    hits = _vocab_hits(path, _load_vocab_snapshot())
    assert not hits, (
        f"{_rel(path)}: quoted vocabulary values not in the KG (snapshot from "
        "inputs/lint/vocab_snapshot.yaml; if the KG changed, run scripts/snapshot_vocab.py)\n  "
        + "\n  ".join(hits)
    )


# ---------------------------------------------------------------------------
# 4. KG-claims register: structural checks (live evaluation is -m kg)
# ---------------------------------------------------------------------------

def _load_claims() -> list[dict]:
    claims = yaml.safe_load((LINT_DIR / "kg_claims.yaml").read_text(encoding="utf-8"))
    assert isinstance(claims, list) and claims
    return claims


def test_kg_claims_register_is_well_formed():
    claims = _load_claims()
    ids = [c["id"] for c in claims]
    assert len(set(ids)) == len(ids), "duplicate claim id"
    for c in claims:
        assert {"id", "expect", "used_in"} <= set(c), c["id"]
        assert c.get("cypher") or c.get("source"), f"{c['id']}: needs cypher or source"
        assert isinstance(c["expect"], dict) and c["expect"], c["id"]
        tol = c.get("tolerance") or {}
        assert set(tol) <= {"abs", "rel"}, f"{c['id']}: tolerance keys must be abs/rel"


@pytest.mark.parametrize("claim", _load_claims(), ids=lambda c: c["id"])
def test_kg_claims_used_in_exist(claim: dict):
    missing = [p for p in claim["used_in"] if not (REPO / p).exists()]
    assert not missing, f"{claim['id']}: used_in paths do not exist: {missing}"


# ---------------------------------------------------------------------------
# 5. CLAUDE.md tool table stays a routing table
# ---------------------------------------------------------------------------

CLAUDE_ROW_MAX_CHARS = 700
_SPEC_REF_RE = re.compile(r"§")
_CONFIG_INTERNALS_RE = re.compile(r"\b(?:term_verbose|term_details_compact|bridges_out|hierarchy_rels)\b")
_CHANGELOG_RE = re.compile(r"\b(?:removed|successor of|renamed from|superseded by)\b", re.I)
_FOOTNOTE_RE = re.compile(r"`?\[(?:AQ|ENR|TRUST)\]`?")


@pytest.fixture(scope="module")
def claude_rows() -> dict[str, str]:
    rows = claude_md_rows()
    assert rows, "no tool-table rows parsed from CLAUDE.md"
    return rows


def test_claude_md_table_row_length(claude_rows):
    long = {t: len(r) for t, r in claude_rows.items() if len(r) > CLAUDE_ROW_MAX_CHARS}
    assert not long, (
        f"CLAUDE.md rows over {CLAUDE_ROW_MAX_CHARS} chars (move detail to docs://tools/<name>):\n  "
        + "\n  ".join(f"{t}: {n}" for t, n in sorted(long.items(), key=lambda kv: -kv[1]))
    )


def test_claude_md_table_no_spec_refs(claude_rows):
    bad = [t for t, r in claude_rows.items() if _SPEC_REF_RE.search(r)]
    assert not bad, f"CLAUDE.md rows cite spec sections (§): {bad}"


def test_claude_md_table_no_config_internals(claude_rows):
    bad = {t: sorted(set(_CONFIG_INTERNALS_RE.findall(r))) for t, r in claude_rows.items()
           if _CONFIG_INTERNALS_RE.search(r)}
    assert not bad, f"CLAUDE.md rows leak ONTOLOGY_CONFIG internals: {bad}"


def test_claude_md_table_no_changelog_words(claude_rows):
    bad = {}
    for t, r in claude_rows.items():
        body = _FOOTNOTE_RE.sub("", r)
        words = sorted(set(w.lower() for w in _CHANGELOG_RE.findall(body)))
        if words:
            bad[t] = words
    assert not bad, (
        "CLAUDE.md rows carry changelog language (what a field replaced belongs in CHANGELOG.md):\n  "
        + "\n  ".join(f"{t}: {w}" for t, w in bad.items())
    )


# ---------------------------------------------------------------------------
# 6. Tool inventory consistent across every surface
# ---------------------------------------------------------------------------

# Tools that start_here.md is allowed not to mention. Keep empty; add a name
# only with a reason.
START_HERE_EXEMPT: set[str] = set()


def _expected_tools_constant() -> set[str]:
    src = (REPO / "tests" / "unit" / "test_tool_wrappers.py").read_text(encoding="utf-8")
    m = re.search(r"EXPECTED_TOOLS\s*=\s*\[(.*?)\]", src, re.S)
    assert m, "EXPECTED_TOOLS not found in tests/unit/test_tool_wrappers.py"
    return set(re.findall(r'"(\w+)"', m.group(1)))


def _inventory() -> dict[str, set[str]]:
    registry = registered_tool_names()
    return {
        "tools.py @mcp.tool": registry,
        "test_tool_wrappers.EXPECTED_TOOLS": _expected_tools_constant(),
        "references/tools/*.md": {p.stem for p in (REFS / "tools").glob("*.md")},
        "inputs/tools/*.yaml": {p.stem for p in (INPUTS / "tools").glob("*.yaml")},
        "CLAUDE.md table": set(claude_md_rows()),
    }


def test_tool_inventory_consistent():
    sets = _inventory()
    universe = set().union(*sets.values())
    problems = []
    for name in sorted(universe):
        missing = [k for k, v in sets.items() if name not in v]
        if missing:
            problems.append(f"{name}: missing from {missing}")
    assert not problems, "tool inventory drift:\n  " + "\n  ".join(problems)


def test_tool_inventory_start_here_mentions_every_tool():
    registry = registered_tool_names()
    text = START_HERE.read_text(encoding="utf-8")
    mentioned = {t for t in re.findall(r"`(\w+)`", text) if t in registry}
    missing = sorted(registry - mentioned - START_HERE_EXEMPT)
    assert not missing, f"start_here.md never mentions: {missing}"
    stale_exempt = sorted(START_HERE_EXEMPT & mentioned)
    assert not stale_exempt, f"START_HERE_EXEMPT entries now mentioned — drop them: {stale_exempt}"


def test_tool_inventory_count_claims_in_claude_md_and_readme():
    """'N tools' in CLAUDE.md / examples README / analysis docs equals the registry.

    tests/unit/test_about_content.py::test_tool_count_claims_match_registry
    already covers guide/*.md and server.py; this extends the same rule to the
    remaining surfaces and to the kg_claims register's tool_count entry.
    """
    total = len(registered_tool_names())
    files = [CLAUDE_MD, EXAMPLES_DIR / "README.md"] + sorted((REFS / "analysis").glob("*.md")) \
        + sorted((REFS / "ontologies").glob("*.md"))
    bad = []
    for f in files:
        for i, line in enumerate(_lines(f), 1):
            for n in re.findall(r"\b(\d+)\s+tools\b", line):
                # small counts ("the 7 chemistry tools") are sub-family sizes,
                # not inventory claims
                if int(n) >= 30 and int(n) != total:
                    bad.append(f"{_rel(f)}:{i}: '{n} tools' (registry has {total})")
    for c in _load_claims():
        if c.get("source") == "tool_registry" and c["expect"].get("tools") != total:
            bad.append(f"inputs/lint/kg_claims.yaml: {c['id']} expects {c['expect']} (registry has {total})")
    assert not bad, "tool-count claim drift:\n  " + "\n  ".join(bad)


def test_lint_description_length_flags_long():
    """`lint_description_length` reports one line per over-budget description."""
    from scripts.build_about_content import DESCRIPTION_MAX_CHARS, lint_description_length

    assert DESCRIPTION_MAX_CHARS == 600
    out = lint_description_length(
        {"t": {"description": "x" * 601, "parameters": {}, "output_schema": None}}
    )
    assert out == ["t: description 601 chars > 600"]
    assert (
        lint_description_length(
            {"t": {"description": "ok", "parameters": {}, "output_schema": None}}
        )
        == []
    )


def test_every_tool_description_within_budget():
    """Every registered tool's description fits the five-slot budget."""
    from scripts.build_about_content import get_tool_schemas, lint_description_length

    assert lint_description_length(get_tool_schemas()) == []
